"""initial domain model batch A

Revision ID: 26533d4669bd
Revises: 
Create Date: 2026-08-17 10:14:09.986090

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '26533d4669bd'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_scale',
    sa.Column('scale_code', sa.String(length=64), nullable=False),
    sa.Column('scale_name', sa.String(length=128), nullable=False),
    sa.Column('scale_type', sa.String(length=32), nullable=False),
    sa.Column('clinical_purpose', sa.Text(), nullable=True),
    sa.Column('applicable_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scale_code')
    )
    op.create_index('idx_assessment_scale_status', 'assessment_scale', ['status', 'deleted'], unique=False)
    op.create_table('dialogue_script',
    sa.Column('script_code', sa.String(length=64), nullable=False),
    sa.Column('script_type', sa.String(length=32), nullable=False),
    sa.Column('cicare_stage', sa.String(length=32), nullable=True),
    sa.Column('audience_type', sa.String(length=32), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('version_code', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_code', 'version_code', 'language_code', name='uq_script_version_language')
    )
    op.create_index('idx_dialogue_script_type', 'dialogue_script', ['script_type', 'deleted'], unique=False)
    op.create_table('interaction_rule',
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_index('idx_interaction_rule_status_priority', 'interaction_rule', ['status', 'priority'], unique=False)
    op.create_table('patient',
    sa.Column('patient_no', sa.String(length=64), nullable=False, comment='系统患者唯一编号'),
    sa.Column('his_patient_id', sa.String(length=64), nullable=True, comment='HIS患者主索引'),
    sa.Column('patient_name', sa.String(length=128), nullable=False, comment='患者姓名'),
    sa.Column('sex', sa.String(length=16), nullable=True, comment='性别'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='联系方式'),
    sa.Column('id_card_ciphertext', sa.Text(), nullable=True, comment='加密后的身份证号'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_no')
    )
    op.create_index('idx_patient_deleted', 'patient', ['deleted'], unique=False)
    op.create_index('idx_patient_name', 'patient', ['patient_name'], unique=False)
    op.create_index(op.f('ix_patient_his_patient_id'), 'patient', ['his_patient_id'], unique=False)
    op.create_table('assessment_scale_version',
    sa.Column('scale_id', sa.BigInteger(), nullable=False),
    sa.Column('version_code', sa.String(length=64), nullable=False),
    sa.Column('version_name', sa.String(length=128), nullable=False),
    sa.Column('publish_status', sa.String(length=32), nullable=False),
    sa.Column('effective_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scale_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['scale_id'], ['assessment_scale.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scale_id', 'version_code', name='uq_scale_version_code')
    )
    op.create_index('idx_scale_version_status', 'assessment_scale_version', ['scale_id', 'publish_status', 'deleted'], unique=False)
    op.create_table('patient_encounter',
    sa.Column('encounter_no', sa.String(length=64), nullable=False, comment='住院过程编号'),
    sa.Column('patient_id', sa.BigInteger(), nullable=False, comment='患者ID'),
    sa.Column('inpatient_no', sa.String(length=64), nullable=True, comment='医院住院号'),
    sa.Column('department_code', sa.String(length=64), nullable=True, comment='科室编码'),
    sa.Column('department_name', sa.String(length=128), nullable=True, comment='科室名称快照'),
    sa.Column('ward_name', sa.String(length=128), nullable=True, comment='病区'),
    sa.Column('bed_no', sa.String(length=32), nullable=True, comment='床号'),
    sa.Column('admission_time', sa.DateTime(timezone=True), nullable=False, comment='入院时间'),
    sa.Column('discharge_time', sa.DateTime(timezone=True), nullable=True, comment='出院时间'),
    sa.Column('diagnosis_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='诊断快照'),
    sa.Column('encounter_status', sa.String(length=32), nullable=False, comment='住院状态'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_no')
    )
    op.create_index('idx_patient_encounter_patient', 'patient_encounter', ['patient_id', 'deleted'], unique=False)
    op.create_index('idx_patient_encounter_status', 'patient_encounter', ['encounter_status', 'deleted'], unique=False)
    op.create_index(op.f('ix_patient_encounter_inpatient_no'), 'patient_encounter', ['inpatient_no'], unique=False)
    op.create_table('assessment_rule',
    sa.Column('scale_version_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['scale_version_id'], ['assessment_scale_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scale_version_id', 'rule_code', name='uq_rule_version_code')
    )
    op.create_index('idx_rule_version_priority', 'assessment_rule', ['scale_version_id', 'priority'], unique=False)
    op.create_table('assessment_section',
    sa.Column('scale_version_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_section_id', sa.BigInteger(), nullable=True),
    sa.Column('section_code', sa.String(length=64), nullable=False),
    sa.Column('section_name', sa.String(length=128), nullable=False),
    sa.Column('section_description', sa.Text(), nullable=True),
    sa.Column('display_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['assessment_section.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scale_version_id'], ['assessment_scale_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scale_version_id', 'section_code', name='uq_section_version_code')
    )
    op.create_index('idx_section_version_sort', 'assessment_section', ['scale_version_id', 'sort_no'], unique=False)
    op.create_table('care_task',
    sa.Column('task_no', sa.String(length=64), nullable=False, comment='任务编号'),
    sa.Column('patient_id', sa.BigInteger(), nullable=False, comment='患者ID'),
    sa.Column('encounter_id', sa.BigInteger(), nullable=False, comment='住院记录ID'),
    sa.Column('parent_task_id', sa.BigInteger(), nullable=True, comment='父任务ID'),
    sa.Column('task_type', sa.String(length=32), nullable=False, comment='任务类型'),
    sa.Column('task_name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('task_source', sa.String(length=32), nullable=False, comment='任务来源'),
    sa.Column('collection_mode', sa.String(length=32), nullable=True, comment='采集模式：traditional_form或ai_dialogue；子任务从父任务继承'),
    sa.Column('task_status', sa.String(length=32), nullable=False, comment='任务状态'),
    sa.Column('assigned_nurse_id', sa.BigInteger(), nullable=True, comment='负责护士ID'),
    sa.Column('planned_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('need_manual_intervention', sa.Boolean(), nullable=False),
    sa.Column('intervention_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['encounter_id'], ['patient_encounter.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['care_task.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    op.create_index('idx_care_task_encounter', 'care_task', ['encounter_id', 'deleted'], unique=False)
    op.create_index('idx_care_task_parent', 'care_task', ['parent_task_id'], unique=False)
    op.create_index('idx_care_task_patient', 'care_task', ['patient_id', 'deleted'], unique=False)
    op.create_index('idx_care_task_status', 'care_task', ['task_status', 'deleted'], unique=False)
    op.create_table('assessment_action_definition',
    sa.Column('scale_version_id', sa.BigInteger(), nullable=False),
    sa.Column('action_code', sa.String(length=64), nullable=False),
    sa.Column('action_group', sa.String(length=64), nullable=True),
    sa.Column('action_name', sa.String(length=256), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('input_type', sa.String(length=32), nullable=False),
    sa.Column('allow_other', sa.Boolean(), nullable=False),
    sa.Column('trigger_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['scale_version_id'], ['assessment_scale_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_rule_id'], ['assessment_rule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scale_version_id', 'action_code', name='uq_action_version_code')
    )
    op.create_index('idx_action_version_sort', 'assessment_action_definition', ['scale_version_id', 'sort_no'], unique=False)
    op.create_table('assessment_instance',
    sa.Column('instance_no', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('encounter_id', sa.BigInteger(), nullable=False),
    sa.Column('scale_id', sa.BigInteger(), nullable=False),
    sa.Column('scale_version_id', sa.BigInteger(), nullable=False),
    sa.Column('assessment_scene', sa.String(length=32), nullable=False),
    sa.Column('instance_status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessor_type', sa.String(length=32), nullable=True),
    sa.Column('assessor_id', sa.BigInteger(), nullable=True),
    sa.Column('patient_name_snapshot', sa.String(length=128), nullable=False),
    sa.Column('sex_snapshot', sa.String(length=16), nullable=True),
    sa.Column('age_snapshot', sa.Integer(), nullable=True),
    sa.Column('department_name_snapshot', sa.String(length=128), nullable=True),
    sa.Column('ward_name_snapshot', sa.String(length=128), nullable=True),
    sa.Column('bed_no_snapshot', sa.String(length=32), nullable=True),
    sa.Column('inpatient_no_snapshot', sa.String(length=64), nullable=True),
    sa.Column('diagnosis_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('form_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['encounter_id'], ['patient_encounter.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scale_id'], ['assessment_scale.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scale_version_id'], ['assessment_scale_version.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['care_task.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_no')
    )
    op.create_index('idx_assessment_instance_patient', 'assessment_instance', ['patient_id', 'deleted'], unique=False)
    op.create_index('idx_assessment_instance_status', 'assessment_instance', ['instance_status', 'deleted'], unique=False)
    op.create_index('idx_assessment_instance_task', 'assessment_instance', ['task_id', 'deleted'], unique=False)
    op.create_table('assessment_question',
    sa.Column('scale_version_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('question_code', sa.String(length=64), nullable=False),
    sa.Column('question_name', sa.String(length=256), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('patient_text', sa.Text(), nullable=False),
    sa.Column('nurse_text', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('scored', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('value_precision', sa.Integer(), nullable=True),
    sa.Column('allow_other', sa.Boolean(), nullable=False),
    sa.Column('derived', sa.Boolean(), nullable=False),
    sa.Column('calculation_expression', sa.Text(), nullable=True),
    sa.Column('validation_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['scale_version_id'], ['assessment_scale_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['assessment_section.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scale_version_id', 'question_code', name='uq_question_version_code')
    )
    op.create_index('idx_question_section', 'assessment_question', ['section_id', 'sort_no'], unique=False)
    op.create_index('idx_question_version_sort', 'assessment_question', ['scale_version_id', 'sort_no'], unique=False)
    op.create_table('interaction_session',
    sa.Column('session_no', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('encounter_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_type', sa.String(length=32), nullable=False),
    sa.Column('interaction_type', sa.String(length=32), nullable=False),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('script_version', sa.String(length=64), nullable=True),
    sa.Column('session_status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handoff_required', sa.Boolean(), nullable=False),
    sa.Column('handoff_reason', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['encounter_id'], ['patient_encounter.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['care_task.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_no')
    )
    op.create_index('idx_interaction_session_patient', 'interaction_session', ['patient_id', 'deleted'], unique=False)
    op.create_index('idx_interaction_session_status', 'interaction_session', ['session_status', 'deleted'], unique=False)
    op.create_index('idx_interaction_session_task', 'interaction_session', ['task_id', 'deleted'], unique=False)
    op.create_table('assessment_option',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('option_code', sa.String(length=64), nullable=False),
    sa.Column('option_label', sa.String(length=256), nullable=False),
    sa.Column('option_value', sa.String(length=256), nullable=False),
    sa.Column('clinical_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('risk_tag', sa.String(length=64), nullable=True),
    sa.Column('requires_follow_up', sa.Boolean(), nullable=False),
    sa.Column('extra_input_type', sa.String(length=32), nullable=True),
    sa.Column('extra_input_unit', sa.String(length=32), nullable=True),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'option_code', name='uq_option_question_code')
    )
    op.create_index('idx_option_question_sort', 'assessment_option', ['question_id', 'sort_no'], unique=False)
    op.create_table('assessment_submission',
    sa.Column('submission_no', sa.String(length=64), nullable=False),
    sa.Column('assessment_instance_id', sa.BigInteger(), nullable=False),
    sa.Column('submission_type', sa.String(length=32), nullable=False),
    sa.Column('submitter_type', sa.String(length=32), nullable=False),
    sa.Column('submitter_id', sa.BigInteger(), nullable=True),
    sa.Column('interaction_session_id', sa.BigInteger(), nullable=True),
    sa.Column('submission_status', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('risk_level', sa.String(length=64), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('total_question_count', sa.Integer(), nullable=False),
    sa.Column('answered_question_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['assessment_instance_id'], ['assessment_instance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_session_id'], ['interaction_session.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_no')
    )
    op.create_index('idx_submission_instance_type', 'assessment_submission', ['assessment_instance_id', 'submission_type', 'deleted'], unique=False)
    op.create_index('idx_submission_session', 'assessment_submission', ['interaction_session_id'], unique=False)
    op.create_index('idx_submission_status', 'assessment_submission', ['submission_status', 'deleted'], unique=False)
    op.create_table('interaction_message',
    sa.Column('interaction_session_id', sa.BigInteger(), nullable=False),
    sa.Column('message_no', sa.String(length=64), nullable=False),
    sa.Column('parent_message_id', sa.BigInteger(), nullable=True),
    sa.Column('turn_no', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.String(length=32), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('cicare_stage', sa.String(length=32), nullable=True),
    sa.Column('intent_type', sa.String(length=32), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('asr_text', sa.Text(), nullable=True),
    sa.Column('tts_text', sa.Text(), nullable=True),
    sa.Column('related_question_id', sa.BigInteger(), nullable=True),
    sa.Column('related_clause_id', sa.BigInteger(), nullable=True),
    sa.Column('related_material_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['interaction_session_id'], ['interaction_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['interaction_message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_question_id'], ['assessment_question.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_no')
    )
    op.create_index('idx_interaction_message_occurred', 'interaction_message', ['occurred_at'], unique=False)
    op.create_index('idx_interaction_message_question', 'interaction_message', ['related_question_id'], unique=False)
    op.create_index('idx_interaction_message_session_turn', 'interaction_message', ['interaction_session_id', 'turn_no'], unique=False)
    op.create_table('assessment_answer',
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('answer_type', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_number', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('answer_boolean', sa.Boolean(), nullable=True),
    sa.Column('answer_date', sa.Date(), nullable=True),
    sa.Column('answer_time', sa.Time(timezone=True), nullable=True),
    sa.Column('answer_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer_unit', sa.String(length=32), nullable=True),
    sa.Column('clinical_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source_message_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('value_source', sa.String(length=32), nullable=False),
    sa.Column('abnormal_flag', sa.Boolean(), nullable=False),
    sa.Column('risk_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_question.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['assessment_submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_answer_submission_question')
    )
    op.create_index('idx_answer_abnormal', 'assessment_answer', ['abnormal_flag', 'deleted'], unique=False)
    op.create_index('idx_answer_question', 'assessment_answer', ['question_id'], unique=False)
    op.create_table('assessment_review',
    sa.Column('review_no', sa.String(length=64), nullable=False),
    sa.Column('assessment_instance_id', sa.BigInteger(), nullable=False),
    sa.Column('ai_submission_id', sa.BigInteger(), nullable=True),
    sa.Column('nurse_submission_id', sa.BigInteger(), nullable=True),
    sa.Column('final_submission_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('supplementary_inquiry', sa.Text(), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['ai_submission_id'], ['assessment_submission.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assessment_instance_id'], ['assessment_instance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['final_submission_id'], ['assessment_submission.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nurse_submission_id'], ['assessment_submission.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_no')
    )
    op.create_index('idx_assessment_review_instance', 'assessment_review', ['assessment_instance_id', 'deleted'], unique=False)
    op.create_index('idx_assessment_review_status', 'assessment_review', ['review_status', 'deleted'], unique=False)
    op.create_table('assessment_score',
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('score_code', sa.String(length=64), nullable=False),
    sa.Column('score_name', sa.String(length=128), nullable=False),
    sa.Column('score_type', sa.String(length=32), nullable=False),
    sa.Column('score_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('risk_level', sa.String(length=64), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('calculation_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['submission_id'], ['assessment_submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'score_code', name='uq_submission_score_code')
    )
    op.create_index('idx_assessment_score_submission', 'assessment_score', ['submission_id'], unique=False)
    op.create_table('interaction_event',
    sa.Column('interaction_session_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('handled_status', sa.String(length=32), nullable=False),
    sa.Column('handled_by', sa.String(length=64), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['interaction_session_id'], ['interaction_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['interaction_message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['interaction_rule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interaction_event_session', 'interaction_event', ['interaction_session_id', 'deleted'], unique=False)
    op.create_index('idx_interaction_event_status', 'interaction_event', ['handled_status', 'deleted'], unique=False)
    op.create_table('interaction_message_feedback',
    sa.Column('interaction_session_id', sa.BigInteger(), nullable=False),
    sa.Column('interaction_message_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_no', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('feedback_type', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('issue_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['interaction_message_id'], ['interaction_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_session_id'], ['interaction_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interaction_message_id', 'reviewer_id', name='uq_message_feedback_reviewer')
    )
    op.create_index('idx_message_feedback_session', 'interaction_message_feedback', ['interaction_session_id', 'turn_no'], unique=False)
    op.create_index('idx_message_feedback_type', 'interaction_message_feedback', ['feedback_type'], unique=False)
    op.create_table('assessment_answer_option',
    sa.Column('assessment_answer_id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('option_code_snapshot', sa.String(length=64), nullable=False),
    sa.Column('option_label_snapshot', sa.String(length=256), nullable=False),
    sa.Column('clinical_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('extra_text', sa.Text(), nullable=True),
    sa.Column('extra_number', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('extra_unit', sa.String(length=32), nullable=True),
    sa.Column('selected_flag', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建人账号或系统标识'),
    sa.Column('updator', sa.String(length=64), nullable=True, comment='最后更新人账号或系统标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0未删除，1已删除'),
    sa.ForeignKeyConstraint(['assessment_answer_id'], ['assessment_answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['assessment_option.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_answer_id', 'option_id', name='uq_answer_option')
    )
    op.create_index('idx_answer_option_answer', 'assessment_answer_option', ['assessment_answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_answer_option_answer', table_name='assessment_answer_option')
    op.drop_table('assessment_answer_option')
    op.drop_index('idx_message_feedback_type', table_name='interaction_message_feedback')
    op.drop_index('idx_message_feedback_session', table_name='interaction_message_feedback')
    op.drop_table('interaction_message_feedback')
    op.drop_index('idx_interaction_event_status', table_name='interaction_event')
    op.drop_index('idx_interaction_event_session', table_name='interaction_event')
    op.drop_table('interaction_event')
    op.drop_index('idx_assessment_score_submission', table_name='assessment_score')
    op.drop_table('assessment_score')
    op.drop_index('idx_assessment_review_status', table_name='assessment_review')
    op.drop_index('idx_assessment_review_instance', table_name='assessment_review')
    op.drop_table('assessment_review')
    op.drop_index('idx_answer_question', table_name='assessment_answer')
    op.drop_index('idx_answer_abnormal', table_name='assessment_answer')
    op.drop_table('assessment_answer')
    op.drop_index('idx_interaction_message_session_turn', table_name='interaction_message')
    op.drop_index('idx_interaction_message_question', table_name='interaction_message')
    op.drop_index('idx_interaction_message_occurred', table_name='interaction_message')
    op.drop_table('interaction_message')
    op.drop_index('idx_submission_status', table_name='assessment_submission')
    op.drop_index('idx_submission_session', table_name='assessment_submission')
    op.drop_index('idx_submission_instance_type', table_name='assessment_submission')
    op.drop_table('assessment_submission')
    op.drop_index('idx_option_question_sort', table_name='assessment_option')
    op.drop_table('assessment_option')
    op.drop_index('idx_interaction_session_task', table_name='interaction_session')
    op.drop_index('idx_interaction_session_status', table_name='interaction_session')
    op.drop_index('idx_interaction_session_patient', table_name='interaction_session')
    op.drop_table('interaction_session')
    op.drop_index('idx_question_version_sort', table_name='assessment_question')
    op.drop_index('idx_question_section', table_name='assessment_question')
    op.drop_table('assessment_question')
    op.drop_index('idx_assessment_instance_task', table_name='assessment_instance')
    op.drop_index('idx_assessment_instance_status', table_name='assessment_instance')
    op.drop_index('idx_assessment_instance_patient', table_name='assessment_instance')
    op.drop_table('assessment_instance')
    op.drop_index('idx_action_version_sort', table_name='assessment_action_definition')
    op.drop_table('assessment_action_definition')
    op.drop_index('idx_care_task_status', table_name='care_task')
    op.drop_index('idx_care_task_patient', table_name='care_task')
    op.drop_index('idx_care_task_parent', table_name='care_task')
    op.drop_index('idx_care_task_encounter', table_name='care_task')
    op.drop_table('care_task')
    op.drop_index('idx_section_version_sort', table_name='assessment_section')
    op.drop_table('assessment_section')
    op.drop_index('idx_rule_version_priority', table_name='assessment_rule')
    op.drop_table('assessment_rule')
    op.drop_index(op.f('ix_patient_encounter_inpatient_no'), table_name='patient_encounter')
    op.drop_index('idx_patient_encounter_status', table_name='patient_encounter')
    op.drop_index('idx_patient_encounter_patient', table_name='patient_encounter')
    op.drop_table('patient_encounter')
    op.drop_index('idx_scale_version_status', table_name='assessment_scale_version')
    op.drop_table('assessment_scale_version')
    op.drop_index(op.f('ix_patient_his_patient_id'), table_name='patient')
    op.drop_index('idx_patient_name', table_name='patient')
    op.drop_index('idx_patient_deleted', table_name='patient')
    op.drop_table('patient')
    op.drop_index('idx_interaction_rule_status_priority', table_name='interaction_rule')
    op.drop_table('interaction_rule')
    op.drop_index('idx_dialogue_script_type', table_name='dialogue_script')
    op.drop_table('dialogue_script')
    op.drop_index('idx_assessment_scale_status', table_name='assessment_scale')
    op.drop_table('assessment_scale')
    # ### end Alembic commands ###
