"""Initial migration: create core tables

Revision ID: acd1b408c6d6
Revises: 
Create Date: 2026-08-16 22:42:58.401346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acd1b408c6d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_states', 'state_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='智能体状态快照',
               existing_nullable=False)
    op.alter_column('agent_states', 'snapshot_reason',
               existing_type=sa.VARCHAR(length=50),
               comment='快照原因',
               existing_comment='快照原因：定期备份、错误前保存、手动触发',
               existing_nullable=False)
    op.drop_index(op.f('idx_agent_states_created_at'), table_name='agent_states')
    op.create_index('idx_agent_states_created_at', 'agent_states', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_table_comment(
        'agent_states',
        existing_comment='智能体状态快照表，用于故障恢复和调试',
        schema=None
    )
    op.alter_column('assessment_tasks', 'task_no',
               existing_type=sa.VARCHAR(length=32),
               comment='任务编号',
               existing_comment='任务编号，格式：TASK-{timestamp}-{random}',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'patient_id',
               existing_type=sa.BIGINT(),
               comment='患者ID',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'nurse_id',
               existing_type=sa.BIGINT(),
               comment='创建任务的护士ID',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'department_id',
               existing_type=sa.BIGINT(),
               comment='科室ID',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'form_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='量表ID列表',
               existing_comment='量表ID列表，JSON数组格式',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               comment='任务类型',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('idx_assessment_tasks_created_at'), table_name='assessment_tasks')
    op.create_index('idx_assessment_tasks_created_at', 'assessment_tasks', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_table_comment(
        'assessment_tasks',
        existing_comment='评估任务主表',
        schema=None
    )
    op.alter_column('consent_forms', 'form_type',
               existing_type=sa.VARCHAR(length=50),
               comment='表单类型',
               existing_nullable=False)
    op.alter_column('consent_forms', 'form_content',
               existing_type=sa.TEXT(),
               comment='知情同意书内容',
               existing_nullable=False)
    op.alter_column('consent_forms', 'is_signed',
               existing_type=sa.BOOLEAN(),
               comment='是否已签署',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('consent_forms', 'signature_data',
               existing_type=sa.TEXT(),
               comment='签名图片base64或URL',
               existing_comment='患者签名数据，可以是base64图片或OSS URL',
               existing_nullable=True)
    op.drop_table_comment(
        'consent_forms',
        existing_comment='知情同意书签署表',
        schema=None
    )
    op.add_column('dialog_messages', sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外元数据'))
    op.alter_column('dialog_messages', 'message_id',
               existing_type=sa.VARCHAR(length=64),
               comment='消息UUID',
               existing_nullable=False)
    op.alter_column('dialog_messages', 'turn_number',
               existing_type=sa.INTEGER(),
               comment='对话轮次',
               existing_comment='对话轮次，每一对user+assistant为一轮',
               existing_nullable=False)
    op.alter_column('dialog_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='角色',
               existing_nullable=False)
    op.alter_column('dialog_messages', 'content',
               existing_type=sa.TEXT(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('dialog_messages', 'content_type',
               existing_type=sa.VARCHAR(length=20),
               comment='内容类型',
               existing_nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('dialog_messages', 'tool_calls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='工具调用记录',
               existing_comment='工具调用详情，JSON数组格式',
               existing_nullable=True)
    op.alter_column('dialog_messages', 'audio_url',
               existing_type=sa.VARCHAR(length=255),
               comment='语音文件URL',
               existing_nullable=True)
    op.drop_index(op.f('idx_dialog_messages_created_at'), table_name='dialog_messages')
    op.create_index('idx_dialog_messages_created_at', 'dialog_messages', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_table_comment(
        'dialog_messages',
        existing_comment='对话消息表，记录所有对话历史',
        schema=None
    )
    op.drop_column('dialog_messages', 'metadata')
    op.add_column('dialog_sessions', sa.Column('agent_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='智能体元数据'))
    op.alter_column('dialog_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=64),
               comment='会话ID（进程号）',
               existing_nullable=False)
    op.alter_column('dialog_sessions', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               comment='智能体类型',
               existing_nullable=False)
    op.alter_column('dialog_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='会话状态',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('dialog_sessions', 'redis_state_key',
               existing_type=sa.VARCHAR(length=128),
               comment='Redis状态存储key',
               existing_comment='Redis中存储智能体状态的key',
               existing_nullable=True)
    op.drop_index(op.f('idx_dialog_sessions_last_active'), table_name='dialog_sessions')
    op.create_index('idx_dialog_sessions_last_active', 'dialog_sessions', ['last_active_at'], unique=False, postgresql_ops={'last_active_at': 'DESC'})
    op.drop_table_comment(
        'dialog_sessions',
        existing_comment='对话会话表，记录各智能体会话状态',
        schema=None
    )
    op.drop_column('dialog_sessions', 'metadata')
    op.alter_column('education_records', 'education_type',
               existing_type=sa.VARCHAR(length=50),
               comment='宣教类别',
               existing_nullable=False)
    op.alter_column('education_records', 'material_id',
               existing_type=sa.VARCHAR(length=50),
               comment='宣教材料ID',
               existing_nullable=False)
    op.alter_column('education_records', 'level',
               existing_type=sa.INTEGER(),
               comment='宣教级别',
               existing_comment='宣教级别：1-基础宣教，2-详细宣教，3-重点宣教',
               existing_nullable=True)
    op.alter_column('education_records', 'is_completed',
               existing_type=sa.BOOLEAN(),
               comment='是否完成宣读',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_table_comment(
        'education_records',
        existing_comment='宣教记录表，记录分级宣教执行情况',
        schema=None
    )
    op.drop_constraint(op.f('education_records_level_check'), 'education_records', type_='check')
    op.alter_column('extracted_fields', 'form_id',
               existing_type=sa.VARCHAR(length=50),
               comment='量表ID',
               existing_nullable=False)
    op.alter_column('extracted_fields', 'field_key',
               existing_type=sa.VARCHAR(length=100),
               comment='字段键名',
               existing_nullable=False)
    op.alter_column('extracted_fields', 'field_value',
               existing_type=sa.TEXT(),
               comment='字段值',
               existing_nullable=True)
    op.alter_column('extracted_fields', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='抽取置信度',
               existing_comment='抽取置信度，低于0.7需要人工确认',
               existing_nullable=True)
    op.alter_column('extracted_fields', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               comment='是否已人工确认',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('extracted_fields', 'confirmed_by',
               existing_type=sa.BIGINT(),
               comment='确认人ID',
               existing_nullable=True)
    op.drop_index(op.f('idx_extracted_fields_confidence'), table_name='extracted_fields')
    op.create_index('idx_extracted_fields_confidence', 'extracted_fields', ['confidence'], unique=False, postgresql_ops={'confidence': 'DESC'})
    op.drop_table_comment(
        'extracted_fields',
        existing_comment='字段抽取结果表，记录从对话中抽取的结构化字段',
        schema=None
    )
    op.drop_constraint(op.f('extracted_fields_confidence_check'), 'extracted_fields', type_='check')
    op.alter_column('nurse_ratings', 'rating_type',
               existing_type=sa.VARCHAR(length=20),
               comment='评分类型',
               existing_nullable=False)
    op.alter_column('nurse_ratings', 'comment',
               existing_type=sa.TEXT(),
               comment='护士意见',
               existing_nullable=True)
    op.drop_index(op.f('idx_nurse_ratings_created_at'), table_name='nurse_ratings')
    op.create_index('idx_nurse_ratings_created_at', 'nurse_ratings', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_table_comment(
        'nurse_ratings',
        existing_comment='护理评分表，用于收集护士对AI对话的反馈',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'nurse_ratings',
        '护理评分表，用于收集护士对AI对话的反馈',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_nurse_ratings_created_at', table_name='nurse_ratings', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_nurse_ratings_created_at'), 'nurse_ratings', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('nurse_ratings', 'comment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='护士意见',
               existing_nullable=True)
    op.alter_column('nurse_ratings', 'rating_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='评分类型',
               existing_nullable=False)
    op.create_check_constraint(op.f('extracted_fields_confidence_check'), 'extracted_fields', 'confidence >= 0::double precision AND confidence <= 1::double precision')
    op.create_table_comment(
        'extracted_fields',
        '字段抽取结果表，记录从对话中抽取的结构化字段',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_extracted_fields_confidence', table_name='extracted_fields', postgresql_ops={'confidence': 'DESC'})
    op.create_index(op.f('idx_extracted_fields_confidence'), 'extracted_fields', [sa.literal_column('confidence DESC')], unique=False)
    op.alter_column('extracted_fields', 'confirmed_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='确认人ID',
               existing_nullable=True)
    op.alter_column('extracted_fields', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已人工确认',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('extracted_fields', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='抽取置信度，低于0.7需要人工确认',
               existing_comment='抽取置信度',
               existing_nullable=True)
    op.alter_column('extracted_fields', 'field_value',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='字段值',
               existing_nullable=True)
    op.alter_column('extracted_fields', 'field_key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='字段键名',
               existing_nullable=False)
    op.alter_column('extracted_fields', 'form_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='量表ID',
               existing_nullable=False)
    op.create_check_constraint(op.f('education_records_level_check'), 'education_records', 'level >= 1 AND level <= 3')
    op.create_table_comment(
        'education_records',
        '宣教记录表，记录分级宣教执行情况',
        existing_comment=None,
        schema=None
    )
    op.alter_column('education_records', 'is_completed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否完成宣读',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('education_records', 'level',
               existing_type=sa.INTEGER(),
               comment='宣教级别：1-基础宣教，2-详细宣教，3-重点宣教',
               existing_comment='宣教级别',
               existing_nullable=True)
    op.alter_column('education_records', 'material_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='宣教材料ID',
               existing_nullable=False)
    op.alter_column('education_records', 'education_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='宣教类别',
               existing_nullable=False)
    op.add_column('dialog_sessions', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='智能体元数据，包括配置参数、工具列表等'))
    op.create_table_comment(
        'dialog_sessions',
        '对话会话表，记录各智能体会话状态',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_dialog_sessions_last_active', table_name='dialog_sessions', postgresql_ops={'last_active_at': 'DESC'})
    op.create_index(op.f('idx_dialog_sessions_last_active'), 'dialog_sessions', [sa.literal_column('last_active_at DESC')], unique=False)
    op.alter_column('dialog_sessions', 'redis_state_key',
               existing_type=sa.VARCHAR(length=128),
               comment='Redis中存储智能体状态的key',
               existing_comment='Redis状态存储key',
               existing_nullable=True)
    op.alter_column('dialog_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='会话状态',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('dialog_sessions', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='智能体类型',
               existing_nullable=False)
    op.alter_column('dialog_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='会话ID（进程号）',
               existing_nullable=False)
    op.drop_column('dialog_sessions', 'agent_metadata')
    op.add_column('dialog_messages', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table_comment(
        'dialog_messages',
        '对话消息表，记录所有对话历史',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_dialog_messages_created_at', table_name='dialog_messages', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_dialog_messages_created_at'), 'dialog_messages', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('dialog_messages', 'audio_url',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='语音文件URL',
               existing_nullable=True)
    op.alter_column('dialog_messages', 'tool_calls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='工具调用详情，JSON数组格式',
               existing_comment='工具调用记录',
               existing_nullable=True)
    op.alter_column('dialog_messages', 'content_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='内容类型',
               existing_nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('dialog_messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('dialog_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='角色',
               existing_nullable=False)
    op.alter_column('dialog_messages', 'turn_number',
               existing_type=sa.INTEGER(),
               comment='对话轮次，每一对user+assistant为一轮',
               existing_comment='对话轮次',
               existing_nullable=False)
    op.alter_column('dialog_messages', 'message_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='消息UUID',
               existing_nullable=False)
    op.drop_column('dialog_messages', 'message_metadata')
    op.create_table_comment(
        'consent_forms',
        '知情同意书签署表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('consent_forms', 'signature_data',
               existing_type=sa.TEXT(),
               comment='患者签名数据，可以是base64图片或OSS URL',
               existing_comment='签名图片base64或URL',
               existing_nullable=True)
    op.alter_column('consent_forms', 'is_signed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已签署',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('consent_forms', 'form_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='知情同意书内容',
               existing_nullable=False)
    op.alter_column('consent_forms', 'form_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='表单类型',
               existing_nullable=False)
    op.create_table_comment(
        'assessment_tasks',
        '评估任务主表',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_assessment_tasks_created_at', table_name='assessment_tasks', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_assessment_tasks_created_at'), 'assessment_tasks', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('assessment_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='任务状态',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('assessment_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='任务类型',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'form_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='量表ID列表，JSON数组格式',
               existing_comment='量表ID列表',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'department_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='科室ID',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'nurse_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='创建任务的护士ID',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'patient_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='患者ID',
               existing_nullable=False)
    op.alter_column('assessment_tasks', 'task_no',
               existing_type=sa.VARCHAR(length=32),
               comment='任务编号，格式：TASK-{timestamp}-{random}',
               existing_comment='任务编号',
               existing_nullable=False)
    op.create_table_comment(
        'agent_states',
        '智能体状态快照表，用于故障恢复和调试',
        existing_comment=None,
        schema=None
    )
    op.drop_index('idx_agent_states_created_at', table_name='agent_states', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_agent_states_created_at'), 'agent_states', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('agent_states', 'snapshot_reason',
               existing_type=sa.VARCHAR(length=50),
               comment='快照原因：定期备份、错误前保存、手动触发',
               existing_comment='快照原因',
               existing_nullable=False)
    op.alter_column('agent_states', 'state_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='智能体状态快照',
               existing_nullable=False)
    # ### end Alembic commands ###
