-- ============================================================
-- 01_patient_task.sql  --  患者与任务域
-- 表: patient, patient_encounter, care_task
-- ============================================================

-- ----------------------------
-- 1. patient  患者主档
-- ----------------------------
CREATE TABLE patient (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_no           VARCHAR(64)  NOT NULL,
    his_patient_id       VARCHAR(64)  NOT NULL DEFAULT '',
    patient_name         VARCHAR(128) NOT NULL,
    sex                  VARCHAR(16)  NOT NULL DEFAULT '',
    birthday             DATE,
    phone                VARCHAR(32)  NOT NULL DEFAULT '',
    id_card_ciphertext   VARCHAR(256) NOT NULL DEFAULT '',
    emergency_contact    VARCHAR(128) NOT NULL DEFAULT '',
    emergency_phone      VARCHAR(32)  NOT NULL DEFAULT '',
    remark               VARCHAR(500) NOT NULL DEFAULT '',
    creator              VARCHAR(64)  NOT NULL DEFAULT '',
    updator              VARCHAR(64)  NOT NULL DEFAULT '',
    create_time          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted              SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  patient IS '患者主档';
COMMENT ON COLUMN patient.patient_no         IS '本系统患者唯一编号';
COMMENT ON COLUMN patient.his_patient_id     IS 'HIS 患者主索引，无 HIS 对接时为空';
COMMENT ON COLUMN patient.id_card_ciphertext IS 'pgcrypto 加密后的身份证号，展示时脱敏';
CREATE UNIQUE INDEX ux_patient_no         ON patient (patient_no)         WHERE deleted = 0;
CREATE        INDEX ix_patient_his_id     ON patient (his_patient_id)     WHERE his_patient_id <> '';

-- ----------------------------
-- 2. patient_encounter  患者住院记录
-- ----------------------------
CREATE TABLE patient_encounter (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_no     VARCHAR(64)  NOT NULL,
    patient_id       BIGINT       NOT NULL,
    inpatient_no     VARCHAR(64)  NOT NULL DEFAULT '',
    department_code  VARCHAR(64)  NOT NULL DEFAULT '',
    department_name  VARCHAR(128) NOT NULL DEFAULT '',
    ward_name        VARCHAR(128) NOT NULL DEFAULT '',
    bed_no           VARCHAR(32)  NOT NULL DEFAULT '',
    admission_time   TIMESTAMP(3),
    discharge_time   TIMESTAMP(3),
    diagnosis_snapshot TEXT       NOT NULL DEFAULT '',
    encounter_status VARCHAR(32)  NOT NULL DEFAULT 'in_hospital',
    creator          VARCHAR(64)  NOT NULL DEFAULT '',
    updator          VARCHAR(64)  NOT NULL DEFAULT '',
    create_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  patient_encounter IS '患者住院记录；科室/病区/诊断保存快照，不依赖可变主数据';
COMMENT ON COLUMN patient_encounter.encounter_status IS 'pending_admission / in_hospital / discharged / cancelled';
CREATE UNIQUE INDEX ux_encounter_no        ON patient_encounter (encounter_no)  WHERE deleted = 0;
CREATE        INDEX ix_encounter_patient   ON patient_encounter (patient_id);

-- ----------------------------
-- 3. care_task  患者护理任务
-- ----------------------------
CREATE TABLE care_task (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no                  VARCHAR(64)  NOT NULL,
    patient_id               BIGINT       NOT NULL,
    encounter_id             BIGINT       NOT NULL,
    parent_task_id           BIGINT       NOT NULL DEFAULT 0,
    task_type                VARCHAR(32)  NOT NULL,
    task_name                VARCHAR(128) NOT NULL,
    task_source              VARCHAR(32)  NOT NULL DEFAULT 'nurse',
    -- 【缺口2】采集模式：traditional_form / ai_dialogue
    -- 父级任务由医护显式选择；子任务为空时，业务层从父任务继承
    collection_mode          VARCHAR(32)  NOT NULL DEFAULT '',
    task_status              VARCHAR(32)  NOT NULL DEFAULT 'pending',
    assigned_nurse_id        BIGINT       NOT NULL DEFAULT 0,
    planned_start_time       TIMESTAMP(3),
    started_at               TIMESTAMP(3),
    completed_at             TIMESTAMP(3),
    need_manual_intervention SMALLINT     NOT NULL DEFAULT 0,
    intervention_reason      VARCHAR(500) NOT NULL DEFAULT '',
    creator                  VARCHAR(64)  NOT NULL DEFAULT '',
    updator                  VARCHAR(64)  NOT NULL DEFAULT '',
    create_time              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                  SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  care_task IS '患者护理任务；入院评估可作父任务，各量表为子任务';
COMMENT ON COLUMN care_task.parent_task_id  IS '父任务 ID；0 表示无父任务';
COMMENT ON COLUMN care_task.task_type       IS 'admission_assessment / specialty_scale / consent / routine_education / medical_education / reassessment';
COMMENT ON COLUMN care_task.collection_mode IS '【缺口2】采集模式: traditional_form / ai_dialogue；父任务必填，子任务为空时业务层从父任务继承';
COMMENT ON COLUMN care_task.task_status     IS 'pending / in_progress / pending_nurse_review / completed / cancelled';
CREATE UNIQUE INDEX ux_care_task_no          ON care_task (task_no)                  WHERE deleted = 0;
CREATE        INDEX ix_care_task_patient_enc ON care_task (patient_id, encounter_id);
CREATE        INDEX ix_care_task_parent      ON care_task (parent_task_id)           WHERE parent_task_id > 0;
CREATE        INDEX ix_care_task_status      ON care_task (task_status)              WHERE deleted = 0;
