-- ============================================================
-- 02_scale_template.sql  --  评估量表模板域
-- 表: assessment_scale, assessment_scale_version,
--     assessment_section, assessment_question,
--     assessment_option, assessment_rule,
--     assessment_action_definition
-- ============================================================

-- ----------------------------
-- 1. assessment_scale  量表主档
-- ----------------------------
CREATE TABLE assessment_scale (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scale_code       VARCHAR(64)  NOT NULL,
    scale_name       VARCHAR(128) NOT NULL,
    scale_type       VARCHAR(32)  NOT NULL,
    clinical_purpose TEXT         NOT NULL DEFAULT '',
    applicable_scope VARCHAR(256) NOT NULL DEFAULT '',
    source_file      VARCHAR(512) NOT NULL DEFAULT '',
    status           VARCHAR(32)  NOT NULL DEFAULT 'draft',
    creator          VARCHAR(64)  NOT NULL DEFAULT '',
    updator          VARCHAR(64)  NOT NULL DEFAULT '',
    create_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_scale IS '评估量表主档（ADL/NRS2002/Braden 等）；只保存量表身份，不含题目';
COMMENT ON COLUMN assessment_scale.scale_type IS 'risk_scale / ability_scale / general_assessment';
COMMENT ON COLUMN assessment_scale.status     IS 'draft / reviewing / published / retired';
CREATE UNIQUE INDEX ux_scale_code ON assessment_scale (scale_code) WHERE deleted = 0;

-- ----------------------------
-- 2. assessment_scale_version  量表版本
-- ----------------------------
CREATE TABLE assessment_scale_version (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scale_id       BIGINT       NOT NULL,
    version_code   VARCHAR(64)  NOT NULL,
    version_name   VARCHAR(128) NOT NULL DEFAULT '',
    publish_status VARCHAR(32)  NOT NULL DEFAULT 'draft',
    effective_time TIMESTAMP(3),
    expire_time    TIMESTAMP(3),
    scale_snapshot JSONB        NOT NULL DEFAULT '{}'::JSONB,
    content_hash   VARCHAR(128) NOT NULL DEFAULT '',
    creator        VARCHAR(64)  NOT NULL DEFAULT '',
    updator        VARCHAR(64)  NOT NULL DEFAULT '',
    create_time    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted        SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_scale_version IS '量表可执行版本；患者评估必须绑定具体版本';
COMMENT ON COLUMN assessment_scale_version.scale_snapshot IS '完整量表 JSON 快照，供历史追溯';
COMMENT ON COLUMN assessment_scale_version.content_hash   IS 'SHA-256，用于判断版本内容是否变化';
CREATE UNIQUE INDEX ux_scale_version_code ON assessment_scale_version (scale_id, version_code) WHERE deleted = 0;
CREATE        INDEX ix_scale_version_scale ON assessment_scale_version (scale_id);

-- ----------------------------
-- 3. assessment_section  量表题目分组
-- ----------------------------
CREATE TABLE assessment_section (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scale_version_id  BIGINT       NOT NULL,
    parent_section_id BIGINT       NOT NULL DEFAULT 0,
    section_code      VARCHAR(64)  NOT NULL,
    section_name      VARCHAR(128) NOT NULL,
    section_description VARCHAR(500) NOT NULL DEFAULT '',
    display_condition JSONB        NOT NULL DEFAULT '{}'::JSONB,
    sort_no           INTEGER      NOT NULL DEFAULT 0,
    creator           VARCHAR(64)  NOT NULL DEFAULT '',
    updator           VARCHAR(64)  NOT NULL DEFAULT '',
    create_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_section IS '量表题目分组（问卷页 / 业务分组）';
CREATE        INDEX ix_section_version ON assessment_section (scale_version_id);

-- ----------------------------
-- 4. assessment_question  评估问题
-- ----------------------------
CREATE TABLE assessment_question (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scale_version_id       BIGINT       NOT NULL,
    section_id             BIGINT       NOT NULL,
    question_code          VARCHAR(64)  NOT NULL,
    question_name          VARCHAR(255) NOT NULL,
    original_text          TEXT         NOT NULL DEFAULT '',
    patient_text           TEXT         NOT NULL DEFAULT '',
    nurse_text             TEXT         NOT NULL DEFAULT '',
    question_type          VARCHAR(32)  NOT NULL,
    value_type             VARCHAR(32)  NOT NULL DEFAULT 'string',
    required               SMALLINT     NOT NULL DEFAULT 1,
    scored                 SMALLINT     NOT NULL DEFAULT 0,
    unit                   VARCHAR(32)  NOT NULL DEFAULT '',
    value_precision        INTEGER      NOT NULL DEFAULT 0,
    allow_other            SMALLINT     NOT NULL DEFAULT 0,
    derived                SMALLINT     NOT NULL DEFAULT 0,
    calculation_expression VARCHAR(500) NOT NULL DEFAULT '',
    validation_rule        JSONB        NOT NULL DEFAULT '{}'::JSONB,
    sort_no                INTEGER      NOT NULL DEFAULT 0,
    creator                VARCHAR(64)  NOT NULL DEFAULT '',
    updator                VARCHAR(64)  NOT NULL DEFAULT '',
    create_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_question IS '量表问题定义；原文/患者文/护士文三种文本并存';
COMMENT ON COLUMN assessment_question.question_type IS 'single_choice / multi_choice / text / number / date / boolean';
COMMENT ON COLUMN assessment_question.value_type    IS 'string / integer / decimal / boolean / date / time / datetime';
COMMENT ON COLUMN assessment_question.derived       IS '1=计算字段（BMI 等），排除在进度分母之外';
CREATE UNIQUE INDEX ux_question_code    ON assessment_question (scale_version_id, question_code) WHERE deleted = 0;
CREATE        INDEX ix_question_version ON assessment_question (scale_version_id);
CREATE        INDEX ix_question_section ON assessment_question (section_id);

-- ----------------------------
-- 5. assessment_option  评估选项
-- ----------------------------
CREATE TABLE assessment_option (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id       BIGINT          NOT NULL,
    option_code       VARCHAR(64)     NOT NULL,
    option_label      VARCHAR(255)    NOT NULL,
    option_value      VARCHAR(128)    NOT NULL DEFAULT '',
    clinical_score    NUMERIC(10,2),
    risk_tag          VARCHAR(64)     NOT NULL DEFAULT '',
    requires_follow_up SMALLINT       NOT NULL DEFAULT 0,
    extra_input_type  VARCHAR(32)     NOT NULL DEFAULT '',
    extra_input_unit  VARCHAR(32)     NOT NULL DEFAULT '',
    sort_no           INTEGER         NOT NULL DEFAULT 0,
    creator           VARCHAR(64)     NOT NULL DEFAULT '',
    updator           VARCHAR(64)     NOT NULL DEFAULT '',
    create_time       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           SMALLINT        NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_option IS '量表选项定义；临床分值仅用于量表计分，与 AI 对话质量评分无关';
COMMENT ON COLUMN assessment_option.clinical_score   IS '该选项的临床分值';
COMMENT ON COLUMN assessment_option.extra_input_type IS '选中后附加输入类型: text / number';
COMMENT ON COLUMN assessment_option.extra_input_unit IS '附加输入单位，如 支/天、次/日、g/日';
CREATE UNIQUE INDEX ux_option_code    ON assessment_option (question_id, option_code) WHERE deleted = 0;
CREATE        INDEX ix_option_question ON assessment_option (question_id);

-- ----------------------------
-- 6. assessment_rule  量表计算与结果规则
-- ----------------------------
CREATE TABLE assessment_rule (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scale_version_id     BIGINT       NOT NULL,
    rule_code            VARCHAR(64)  NOT NULL,
    rule_type            VARCHAR(32)  NOT NULL,
    condition_expression TEXT         NOT NULL DEFAULT '',
    result_payload       JSONB        NOT NULL DEFAULT '{}'::JSONB,
    priority             INTEGER      NOT NULL DEFAULT 0,
    status               VARCHAR(32)  NOT NULL DEFAULT 'enabled',
    creator              VARCHAR(64)  NOT NULL DEFAULT '',
    updator              VARCHAR(64)  NOT NULL DEFAULT '',
    create_time          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted              SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_rule IS '量表计算/风险分级/结果解释/通知规则；规则过程必须可追溯';
COMMENT ON COLUMN assessment_rule.rule_type      IS 'component_score / total_score / risk_level / interpretation / notify_clinician';
COMMENT ON COLUMN assessment_rule.result_payload IS '命中后的分值/等级/解释/动作（JSONB）';
CREATE UNIQUE INDEX ux_rule_code    ON assessment_rule (scale_version_id, rule_code) WHERE deleted = 0;
CREATE        INDEX ix_rule_version ON assessment_rule (scale_version_id);

-- ----------------------------
-- 7. assessment_action_definition  评估处置与措施定义
-- ----------------------------
CREATE TABLE assessment_action_definition (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scale_version_id BIGINT       NOT NULL,
    action_code      VARCHAR(64)  NOT NULL,
    action_group     VARCHAR(64)  NOT NULL DEFAULT '',
    action_name      VARCHAR(128) NOT NULL,
    action_type      VARCHAR(32)  NOT NULL,
    input_type       VARCHAR(32)  NOT NULL DEFAULT 'checkbox',
    allow_other      SMALLINT     NOT NULL DEFAULT 0,
    trigger_rule_id  BIGINT       NOT NULL DEFAULT 0,
    sort_no          INTEGER      NOT NULL DEFAULT 0,
    creator          VARCHAR(64)  NOT NULL DEFAULT '',
    updator          VARCHAR(64)  NOT NULL DEFAULT '',
    create_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_action_definition IS '量表评估后可触发的护理措施/通知/复查等处置定义（Braden/跌倒第二页护理措施用此表）';
COMMENT ON COLUMN assessment_action_definition.action_type IS 'nursing_measure / notify_clinician / reassessment / treatment_suggestion / education';
COMMENT ON COLUMN assessment_action_definition.input_type  IS 'checkbox / boolean / text / datetime';
COMMENT ON COLUMN assessment_action_definition.trigger_rule_id IS '自动推荐或强制触发规则 ID，0 表示无';
CREATE UNIQUE INDEX ux_action_def_code    ON assessment_action_definition (scale_version_id, action_code) WHERE deleted = 0;
CREATE        INDEX ix_action_def_version ON assessment_action_definition (scale_version_id);
