-- ============================================================
-- 03_interaction.sql  --  AI 对话与交互域
-- 表: interaction_session, interaction_message, interaction_event,
--     interaction_rule, dialogue_script,
--     interaction_message_feedback（缺口1新增）
-- ============================================================

-- ----------------------------
-- 1. interaction_session  AI 交互会话
-- ----------------------------
CREATE TABLE interaction_session (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_no       VARCHAR(64)  NOT NULL,
    task_id          BIGINT       NOT NULL,
    patient_id       BIGINT       NOT NULL,
    encounter_id     BIGINT       NOT NULL,
    participant_type VARCHAR(32)  NOT NULL DEFAULT 'patient',
    interaction_type VARCHAR(32)  NOT NULL,
    channel_type     VARCHAR(32)  NOT NULL DEFAULT 'text',
    model_provider   VARCHAR(64)  NOT NULL DEFAULT '',
    model_name       VARCHAR(128) NOT NULL DEFAULT '',
    prompt_version   VARCHAR(64)  NOT NULL DEFAULT '',
    script_version   VARCHAR(64)  NOT NULL DEFAULT '',
    session_status   VARCHAR(32)  NOT NULL DEFAULT 'created',
    started_at       TIMESTAMP(3),
    ended_at         TIMESTAMP(3),
    handoff_required SMALLINT     NOT NULL DEFAULT 0,
    handoff_reason   VARCHAR(500) NOT NULL DEFAULT '',
    ai_summary       TEXT         NOT NULL DEFAULT '',
    creator          VARCHAR(64)  NOT NULL DEFAULT '',
    updator          VARCHAR(64)  NOT NULL DEFAULT '',
    create_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  interaction_session IS 'AI 与患者/家属/护士的一次连续交互会话；一个任务可多次会话（中断后续）';
COMMENT ON COLUMN interaction_session.participant_type IS 'patient / family / nurse';
COMMENT ON COLUMN interaction_session.interaction_type IS 'assessment / consent / education / teachback / nurse_inquiry';
COMMENT ON COLUMN interaction_session.channel_type     IS 'questionnaire / text / voice / mixed';
COMMENT ON COLUMN interaction_session.session_status   IS 'created / in_progress / completed / interrupted / handoff';
CREATE UNIQUE INDEX ux_interaction_session_no   ON interaction_session (session_no) WHERE deleted = 0;
CREATE        INDEX ix_interaction_session_task ON interaction_session (task_id);
CREATE        INDEX ix_interaction_session_pat  ON interaction_session (patient_id);

-- ----------------------------
-- 2. interaction_message  对话消息历史
-- ----------------------------
CREATE TABLE interaction_message (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interaction_session_id BIGINT       NOT NULL,
    message_no             VARCHAR(64)  NOT NULL,
    parent_message_id      BIGINT       NOT NULL DEFAULT 0,
    turn_no                INTEGER      NOT NULL DEFAULT 0,
    role_type              VARCHAR(32)  NOT NULL,
    message_type           VARCHAR(32)  NOT NULL DEFAULT 'text',
    cicare_stage           VARCHAR(32)  NOT NULL DEFAULT '',
    intent_type            VARCHAR(64)  NOT NULL DEFAULT '',
    content_text           TEXT         NOT NULL DEFAULT '',
    audio_url              VARCHAR(512) NOT NULL DEFAULT '',
    asr_text               TEXT         NOT NULL DEFAULT '',
    tts_text               TEXT         NOT NULL DEFAULT '',
    related_question_id    BIGINT       NOT NULL DEFAULT 0,
    related_clause_id      BIGINT       NOT NULL DEFAULT 0,
    related_material_id    BIGINT       NOT NULL DEFAULT 0,
    occurred_at            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator                VARCHAR(64)  NOT NULL DEFAULT '',
    updator                VARCHAR(64)  NOT NULL DEFAULT '',
    create_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  interaction_message IS '对话消息历史；患者原话必须原文保留，不得只保存 AI 总结';
COMMENT ON COLUMN interaction_message.role_type     IS 'ai / patient / family / nurse / system';
COMMENT ON COLUMN interaction_message.message_type  IS 'text / voice / button_selection / system_event';
COMMENT ON COLUMN interaction_message.cicare_stage  IS 'CICARE 阶段：C/I/C/A/R/E';
COMMENT ON COLUMN interaction_message.intent_type   IS 'question / answer / follow_up / education / confirm / handoff';
CREATE UNIQUE INDEX ux_interaction_message_no   ON interaction_message (message_no)                         WHERE deleted = 0;
CREATE        INDEX ix_interaction_message_sess ON interaction_message (interaction_session_id, turn_no);

-- ----------------------------
-- 3. interaction_event  交互事件
-- ----------------------------
CREATE TABLE interaction_event (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interaction_session_id BIGINT       NOT NULL,
    message_id             BIGINT       NOT NULL DEFAULT 0,
    event_type             VARCHAR(64)  NOT NULL,
    rule_id                BIGINT       NOT NULL DEFAULT 0,
    event_payload          JSONB        NOT NULL DEFAULT '{}'::JSONB,
    handled_status         VARCHAR(32)  NOT NULL DEFAULT 'unhandled',
    handled_by             BIGINT       NOT NULL DEFAULT 0,
    handled_at             TIMESTAMP(3),
    creator                VARCHAR(64)  NOT NULL DEFAULT '',
    updator                VARCHAR(64)  NOT NULL DEFAULT '',
    create_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  interaction_event IS '对话中发生的业务事件（命中风险/追问/宣教/转人工）；支持患者画像和护理计划分析';
COMMENT ON COLUMN interaction_event.event_type     IS 'risk_hit / follow_up_triggered / education_triggered / teachback / handoff / patient_refused';
COMMENT ON COLUMN interaction_event.handled_status IS 'unhandled / system_handled / nurse_handled';
CREATE INDEX ix_interaction_event_sess ON interaction_event (interaction_session_id);
CREATE INDEX ix_interaction_event_type ON interaction_event (event_type, handled_status) WHERE deleted = 0;

-- ----------------------------
-- 4. interaction_rule  交互触发规则
-- ----------------------------
CREATE TABLE interaction_rule (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code         VARCHAR(64)  NOT NULL,
    rule_name         VARCHAR(128) NOT NULL,
    scope_type        VARCHAR(32)  NOT NULL,
    scope_id          BIGINT       NOT NULL DEFAULT 0,
    trigger_condition JSONB        NOT NULL DEFAULT '{}'::JSONB,
    action_type       VARCHAR(32)  NOT NULL,
    action_payload    JSONB        NOT NULL DEFAULT '{}'::JSONB,
    priority          INTEGER      NOT NULL DEFAULT 0,
    status            VARCHAR(32)  NOT NULL DEFAULT 'enabled',
    creator           VARCHAR(64)  NOT NULL DEFAULT '',
    updator           VARCHAR(64)  NOT NULL DEFAULT '',
    create_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  interaction_rule IS '对话触发规则：哪些回答或结果需要触发追问/宣教/Teach-back/转人工';
COMMENT ON COLUMN interaction_rule.scope_type  IS 'scale_question / dialogue_intent / education / consent_clause';
COMMENT ON COLUMN interaction_rule.action_type IS 'follow_up / education / teachback / handoff';
CREATE UNIQUE INDEX ux_interaction_rule_code ON interaction_rule (rule_code) WHERE deleted = 0;

-- ----------------------------
-- 5. dialogue_script  对话话术
-- ----------------------------
CREATE TABLE dialogue_script (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_code  VARCHAR(64)  NOT NULL,
    script_type  VARCHAR(32)  NOT NULL,
    cicare_stage VARCHAR(32)  NOT NULL DEFAULT '',
    audience_type VARCHAR(32) NOT NULL DEFAULT 'patient',
    language_code VARCHAR(32) NOT NULL DEFAULT 'zh_CN',
    content_text TEXT         NOT NULL,
    version_code VARCHAR(64)  NOT NULL DEFAULT 'v1',
    status       VARCHAR(32)  NOT NULL DEFAULT 'enabled',
    creator      VARCHAR(64)  NOT NULL DEFAULT '',
    updator      VARCHAR(64)  NOT NULL DEFAULT '',
    create_time  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  dialogue_script IS 'CICARE 开场/追问/宣教/确认/结束话术';
COMMENT ON COLUMN dialogue_script.script_type  IS 'cicare / follow_up / education / consent_confirm / teachback';
COMMENT ON COLUMN dialogue_script.cicare_stage IS 'C/I/C/A/R/E（仅 cicare 类型使用）';
CREATE UNIQUE INDEX ux_dialogue_script_code ON dialogue_script (script_code, version_code) WHERE deleted = 0;

-- ----------------------------
-- 6. interaction_message_feedback  消息反馈（缺口1：RLHF 逐轮标注）
-- ----------------------------
CREATE TABLE interaction_message_feedback (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interaction_session_id BIGINT       NOT NULL,
    interaction_message_id BIGINT       NOT NULL,
    turn_no                INTEGER      NOT NULL DEFAULT 0,
    reviewer_id            BIGINT       NOT NULL,
    feedback_type          VARCHAR(16)  NOT NULL,
    comment                TEXT         NOT NULL DEFAULT '',
    issue_tags             JSONB        NOT NULL DEFAULT '[]'::JSONB,
    reviewed_at            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator                VARCHAR(64)  NOT NULL DEFAULT '',
    updator                VARCHAR(64)  NOT NULL DEFAULT '',
    create_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  interaction_message_feedback IS '【缺口1】护士对 AI 消息的逐轮 RLHF 标注';
COMMENT ON COLUMN interaction_message_feedback.feedback_type IS 'like / dislike';
COMMENT ON COLUMN interaction_message_feedback.issue_tags    IS 'JSONB 数组: follow_up_improper / expression_error / over_education / missed_risk / wrong_answer 等';
COMMENT ON COLUMN interaction_message_feedback.turn_no       IS '冗余轮次，便于回放定位';
CREATE UNIQUE INDEX ux_msg_feedback_reviewer ON interaction_message_feedback (interaction_message_id, reviewer_id) WHERE deleted = 0;
CREATE        INDEX ix_msg_feedback_session  ON interaction_message_feedback (interaction_session_id);
