-- ============================================================
-- 04_assessment_exec.sql  --  评估执行与人机对比域
-- 表: assessment_instance, assessment_submission,
--     assessment_answer, assessment_answer_option,
--     assessment_score, assessment_result_reference,
--     assessment_action_record, assessment_acknowledgement,
--     assessment_signature, assessment_review,
--     assessment_comparison, assessment_comparison_item
-- ============================================================

-- ----------------------------
-- 1. assessment_instance  患者评估实例
-- ----------------------------
CREATE TABLE assessment_instance (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_no             VARCHAR(64)  NOT NULL,
    task_id                 BIGINT       NOT NULL,
    patient_id              BIGINT       NOT NULL,
    encounter_id            BIGINT       NOT NULL,
    scale_id                BIGINT       NOT NULL,
    scale_version_id        BIGINT       NOT NULL,
    assessment_scene        VARCHAR(32)  NOT NULL DEFAULT 'admission',
    instance_status         VARCHAR(32)  NOT NULL DEFAULT 'pending_collection',
    started_at              TIMESTAMP(3),
    confirmed_at            TIMESTAMP(3),
    assessed_at             TIMESTAMP(3),
    assessor_type           VARCHAR(32)  NOT NULL DEFAULT 'patient',
    assessor_id             BIGINT       NOT NULL DEFAULT 0,
    -- 评估快照
    patient_name_snapshot   VARCHAR(128) NOT NULL DEFAULT '',
    sex_snapshot            VARCHAR(16)  NOT NULL DEFAULT '',
    age_snapshot            INTEGER,
    department_name_snapshot VARCHAR(128) NOT NULL DEFAULT '',
    ward_name_snapshot      VARCHAR(128) NOT NULL DEFAULT '',
    bed_no_snapshot         VARCHAR(32)  NOT NULL DEFAULT '',
    inpatient_no_snapshot   VARCHAR(64)  NOT NULL DEFAULT '',
    diagnosis_snapshot      TEXT         NOT NULL DEFAULT '',
    form_snapshot           JSONB        NOT NULL DEFAULT '{}'::JSONB,
    creator                 VARCHAR(64)  NOT NULL DEFAULT '',
    updator                 VARCHAR(64)  NOT NULL DEFAULT '',
    create_time             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                 SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_instance IS '患者评估实例；是 AI/护士/最终结果的共同容器，不直接存多版本结果';
COMMENT ON COLUMN assessment_instance.assessment_scene  IS 'admission / reassessment / transfer / discharge';
COMMENT ON COLUMN assessment_instance.instance_status   IS 'pending_collection / ai_completed / pending_nurse_review / confirmed / voided';
COMMENT ON COLUMN assessment_instance.form_snapshot     IS '本次使用的量表完整 JSON 快照';
CREATE UNIQUE INDEX ux_assessment_instance_no  ON assessment_instance (instance_no) WHERE deleted = 0;
CREATE        INDEX ix_assessment_instance_task ON assessment_instance (task_id);
CREATE        INDEX ix_assessment_instance_pat  ON assessment_instance (patient_id, encounter_id);

-- ----------------------------
-- 2. assessment_submission  评估提交
-- ----------------------------
CREATE TABLE assessment_submission (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_no           VARCHAR(64)  NOT NULL,
    assessment_instance_id  BIGINT       NOT NULL,
    submission_type         VARCHAR(32)  NOT NULL,
    submitter_type          VARCHAR(32)  NOT NULL,
    submitter_id            BIGINT       NOT NULL DEFAULT 0,
    interaction_session_id  BIGINT       NOT NULL DEFAULT 0,
    submission_status       VARCHAR(32)  NOT NULL DEFAULT 'draft',
    total_score             NUMERIC(10,2),
    risk_level              VARCHAR(64)  NOT NULL DEFAULT '',
    result_summary          TEXT         NOT NULL DEFAULT '',
    confidence_score        NUMERIC(5,2),
    -- 【缺口3】进度监控冗余字段
    total_question_count    INTEGER      NOT NULL DEFAULT 0,
    answered_question_count INTEGER      NOT NULL DEFAULT 0,
    submitted_at            TIMESTAMP(3),
    creator                 VARCHAR(64)  NOT NULL DEFAULT '',
    updator                 VARCHAR(64)  NOT NULL DEFAULT '',
    create_time             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                 SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_submission IS 'AI/护士/最终确认各保存一条独立提交，禁止覆盖';
COMMENT ON COLUMN assessment_submission.submission_type         IS 'patient_self / ai_extracted / nurse_independent / final_confirmed';
COMMENT ON COLUMN assessment_submission.submitter_type          IS 'patient / family / ai / nurse';
COMMENT ON COLUMN assessment_submission.submission_status       IS 'draft / submitted / confirmed / revoked';
COMMENT ON COLUMN assessment_submission.confidence_score        IS 'AI 抽取可信度 0.00-1.00，仅 AI 提交使用';
COMMENT ON COLUMN assessment_submission.total_question_count    IS '【缺口3】进度分母：可见且 required=1 的题目数，排除 derived=1 及条件未满足的隐藏题';
COMMENT ON COLUMN assessment_submission.answered_question_count IS '【缺口3】进度分子：本提交中已有答案的题目数，业务层写答案时同步更新';
CREATE UNIQUE INDEX ux_submission_no       ON assessment_submission (submission_no)          WHERE deleted = 0;
CREATE        INDEX ix_submission_instance ON assessment_submission (assessment_instance_id);

-- ----------------------------
-- 3. assessment_answer  评估答案
-- ----------------------------
CREATE TABLE assessment_answer (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id         BIGINT          NOT NULL,
    question_id           BIGINT          NOT NULL,
    answer_type           VARCHAR(32)     NOT NULL,
    answer_text           TEXT            NOT NULL DEFAULT '',
    answer_number         NUMERIC(18,4),
    answer_boolean        SMALLINT,
    answer_date           DATE,
    answer_time           TIME,
    answer_datetime       TIMESTAMP(3),
    answer_unit           VARCHAR(32)     NOT NULL DEFAULT '',
    clinical_score        NUMERIC(10,2),
    source_message_ids    JSONB           NOT NULL DEFAULT '[]'::JSONB,
    extraction_confidence NUMERIC(5,2),
    value_source          VARCHAR(32)     NOT NULL DEFAULT 'patient_input',
    abnormal_flag         SMALLINT        NOT NULL DEFAULT 0,
    risk_tags             JSONB           NOT NULL DEFAULT '[]'::JSONB,
    creator               VARCHAR(64)     NOT NULL DEFAULT '',
    updator               VARCHAR(64)     NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_answer_submission_question UNIQUE (submission_id, question_id)
);
COMMENT ON TABLE  assessment_answer IS '评估答案；唯一约束 (submission_id, question_id) 允许同一题并存 AI/护士/最终答案';
COMMENT ON COLUMN assessment_answer.answer_type        IS '答案主类型: text / number / boolean / date / time / datetime / choice';
COMMENT ON COLUMN assessment_answer.value_source       IS 'patient_input / nurse_input / ai_extracted / system_calculated';
COMMENT ON COLUMN assessment_answer.source_message_ids IS 'AI 答案来源的对话消息 ID 数组（JSONB）';
CREATE INDEX ix_answer_submission ON assessment_answer (submission_id);
CREATE INDEX ix_answer_question   ON assessment_answer (question_id);

-- ----------------------------
-- 4. assessment_answer_option  答案选项明细
-- ----------------------------
CREATE TABLE assessment_answer_option (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_answer_id  BIGINT          NOT NULL,
    option_id             BIGINT          NOT NULL,
    option_code_snapshot  VARCHAR(64)     NOT NULL DEFAULT '',
    option_label_snapshot VARCHAR(255)    NOT NULL DEFAULT '',
    clinical_score        NUMERIC(10,2),
    extra_text            TEXT            NOT NULL DEFAULT '',
    extra_number          NUMERIC(18,4),
    extra_unit            VARCHAR(32)     NOT NULL DEFAULT '',
    selected_flag         SMALLINT        NOT NULL DEFAULT 1,
    creator               VARCHAR(64)     NOT NULL DEFAULT '',
    updator               VARCHAR(64)     NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT        NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_answer_option IS '单/多选题实际选择的选项明细；支持结构化查询和多选计分';
COMMENT ON COLUMN assessment_answer_option.selected_flag IS '1=已选（多选中未选中的选项不入库）';
CREATE INDEX ix_answer_option_answer ON assessment_answer_option (assessment_answer_id);

-- ----------------------------
-- 5. assessment_score  量表临床得分
-- ----------------------------
CREATE TABLE assessment_score (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id      BIGINT          NOT NULL,
    score_code         VARCHAR(64)     NOT NULL,
    score_name         VARCHAR(128)    NOT NULL,
    score_type         VARCHAR(32)     NOT NULL,
    score_value        NUMERIC(10,2),
    max_score          NUMERIC(10,2),
    risk_level         VARCHAR(64)     NOT NULL DEFAULT '',
    interpretation     TEXT            NOT NULL DEFAULT '',
    calculation_detail JSONB           NOT NULL DEFAULT '{}'::JSONB,
    creator            VARCHAR(64)     NOT NULL DEFAULT '',
    updator            VARCHAR(64)     NOT NULL DEFAULT '',
    create_time        TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time        TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted            SMALLINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_score_submission_code UNIQUE (submission_id, score_code)
);
COMMENT ON TABLE  assessment_score IS '量表临床得分（分项/总分/风险等级）；AI/护士/最终分数属于不同提交';
COMMENT ON COLUMN assessment_score.score_type IS 'component_score / total_score / risk_level';
CREATE INDEX ix_score_submission ON assessment_score (submission_id);

-- ----------------------------
-- 6. assessment_result_reference  量表结果引用
-- ----------------------------
CREATE TABLE assessment_result_reference (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_assessment_instance_id BIGINT       NOT NULL,
    reference_code                VARCHAR(64)  NOT NULL,
    target_assessment_instance_id BIGINT       NOT NULL,
    target_submission_id          BIGINT       NOT NULL,
    score_code                    VARCHAR(64)  NOT NULL DEFAULT '',
    score_value_snapshot          NUMERIC(10,2),
    risk_level_snapshot           VARCHAR(64)  NOT NULL DEFAULT '',
    notify_condition_met          SMALLINT     NOT NULL DEFAULT 0,
    creator                       VARCHAR(64)  NOT NULL DEFAULT '',
    updator                       VARCHAR(64)  NOT NULL DEFAULT '',
    create_time                   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                       SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_result_reference IS '综合评估表对其他独立量表结果的引用（ADL/跌倒/压疮/营养快照）';
COMMENT ON COLUMN assessment_result_reference.reference_code IS 'adl_score / fall_risk / pressure_risk / nutrition_risk 等';
CREATE INDEX ix_result_ref_source ON assessment_result_reference (source_assessment_instance_id);

-- ----------------------------
-- 7. assessment_action_record  评估处置与措施记录
-- ----------------------------
CREATE TABLE assessment_action_record (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_instance_id         BIGINT       NOT NULL,
    submission_id                  BIGINT       NOT NULL DEFAULT 0,
    action_definition_id           BIGINT       NOT NULL,
    related_assessment_instance_id BIGINT       NOT NULL DEFAULT 0,
    action_source                  VARCHAR(32)  NOT NULL DEFAULT 'rule_recommended',
    action_status                  VARCHAR(32)  NOT NULL DEFAULT 'pending',
    extra_text                     TEXT         NOT NULL DEFAULT '',
    planned_at                     TIMESTAMP(3),
    executed_at                    TIMESTAMP(3),
    operator_id                    BIGINT       NOT NULL DEFAULT 0,
    creator                        VARCHAR(64)  NOT NULL DEFAULT '',
    updator                        VARCHAR(64)  NOT NULL DEFAULT '',
    create_time                    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                        SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_action_record IS 'Braden/跌倒护理措施逐条记录；AI 建议先标记 pending，护士确认后生效';
COMMENT ON COLUMN assessment_action_record.action_source IS 'rule_recommended / ai_suggested / nurse_selected';
COMMENT ON COLUMN assessment_action_record.action_status IS 'pending / selected / notified / executed / cancelled';
CREATE INDEX ix_action_record_instance ON assessment_action_record (assessment_instance_id);

-- ----------------------------
-- 8. assessment_acknowledgement  评估风险告知确认
-- ----------------------------
CREATE TABLE assessment_acknowledgement (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_instance_id BIGINT       NOT NULL,
    acknowledgement_type   VARCHAR(64)  NOT NULL,
    statement_snapshot     TEXT         NOT NULL DEFAULT '',
    participant_type       VARCHAR(32)  NOT NULL DEFAULT 'patient',
    participant_name       VARCHAR(128) NOT NULL DEFAULT '',
    confirmation_result    VARCHAR(32)  NOT NULL DEFAULT 'unconfirmed',
    confirmed_at           TIMESTAMP(3),
    signature_id           BIGINT       NOT NULL DEFAULT 0,
    creator                VARCHAR(64)  NOT NULL DEFAULT '',
    updator                VARCHAR(64)  NOT NULL DEFAULT '',
    create_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_acknowledgement IS '评估内置风险告知及患者/家属确认结果';
COMMENT ON COLUMN assessment_acknowledgement.acknowledgement_type IS '压疮高危 / 跌倒高危 等';
COMMENT ON COLUMN assessment_acknowledgement.confirmation_result  IS 'confirmed / refused / not_understood / unconfirmed';
CREATE INDEX ix_acknowledgement_instance ON assessment_acknowledgement (assessment_instance_id);

-- ----------------------------
-- 9. assessment_signature  评估签名
-- ----------------------------
CREATE TABLE assessment_signature (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_instance_id BIGINT       NOT NULL,
    submission_id          BIGINT       NOT NULL DEFAULT 0,
    sign_purpose           VARCHAR(64)  NOT NULL,
    signer_type            VARCHAR(32)  NOT NULL,
    signer_id              BIGINT       NOT NULL DEFAULT 0,
    signer_name_snapshot   VARCHAR(128) NOT NULL DEFAULT '',
    signature_method       VARCHAR(32)  NOT NULL DEFAULT 'account_confirm',
    signature_file_url     VARCHAR(512) NOT NULL DEFAULT '',
    signed_at              TIMESTAMP(3),
    creator                VARCHAR(64)  NOT NULL DEFAULT '',
    updator                VARCHAR(64)  NOT NULL DEFAULT '',
    create_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_signature IS 'NRS2002筛查者/ADL评定者/Braden护士/患者/家属签名均覆盖于此';
COMMENT ON COLUMN assessment_signature.sign_purpose      IS 'screener_sign / assessor_sign / nurse_sign / risk_acknowledgement';
COMMENT ON COLUMN assessment_signature.signer_type       IS 'nurse / patient / family / other_clinician';
COMMENT ON COLUMN assessment_signature.signature_method  IS 'account_confirm / handwritten / electronic / paper_record';
CREATE INDEX ix_signature_instance ON assessment_signature (assessment_instance_id);

-- ----------------------------
-- 10. assessment_review  护士评估复核
-- ----------------------------
CREATE TABLE assessment_review (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_no              VARCHAR(64)  NOT NULL,
    assessment_instance_id BIGINT       NOT NULL,
    ai_submission_id       BIGINT       NOT NULL DEFAULT 0,
    nurse_submission_id    BIGINT       NOT NULL DEFAULT 0,
    final_submission_id    BIGINT       NOT NULL DEFAULT 0,
    reviewer_id            BIGINT       NOT NULL,
    review_status          VARCHAR(32)  NOT NULL DEFAULT 'pending',
    supplementary_inquiry  TEXT         NOT NULL DEFAULT '',
    correction_reason      VARCHAR(1000) NOT NULL DEFAULT '',
    reviewed_at            TIMESTAMP(3),
    creator                VARCHAR(64)  NOT NULL DEFAULT '',
    updator                VARCHAR(64)  NOT NULL DEFAULT '',
    create_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_review IS '护士复核记录；只保存复核关系和说明，具体答案仍在 assessment_answer';
COMMENT ON COLUMN assessment_review.review_status IS 'pending / reviewed / returned';
CREATE UNIQUE INDEX ux_review_no       ON assessment_review (review_no)              WHERE deleted = 0;
CREATE        INDEX ix_review_instance ON assessment_review (assessment_instance_id);

-- ----------------------------
-- 11. assessment_comparison  评估人机对比主表
-- ----------------------------
CREATE TABLE assessment_comparison (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_instance_id BIGINT          NOT NULL,
    ai_submission_id       BIGINT          NOT NULL,
    nurse_submission_id    BIGINT          NOT NULL,
    answer_match_rate      NUMERIC(5,2),
    score_difference       NUMERIC(10,2),
    risk_level_same        SMALLINT        NOT NULL DEFAULT 0,
    missed_question_count  INTEGER         NOT NULL DEFAULT 0,
    corrected_answer_count INTEGER         NOT NULL DEFAULT 0,
    comparison_summary     TEXT            NOT NULL DEFAULT '',
    creator                VARCHAR(64)     NOT NULL DEFAULT '',
    updator                VARCHAR(64)     NOT NULL DEFAULT '',
    create_time            TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                SMALLINT        NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_comparison IS 'AI 与护士提交的总体对比；是科研分析的核心基础';
COMMENT ON COLUMN assessment_comparison.answer_match_rate IS '答案一致率 0.00-100.00';
CREATE UNIQUE INDEX ux_comparison_instance ON assessment_comparison (assessment_instance_id, ai_submission_id, nurse_submission_id) WHERE deleted = 0;

-- ----------------------------
-- 12. assessment_comparison_item  对比明细
-- ----------------------------
CREATE TABLE assessment_comparison_item (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comparison_id        BIGINT          NOT NULL,
    compare_object_type  VARCHAR(32)     NOT NULL,
    question_id          BIGINT          NOT NULL DEFAULT 0,
    score_code           VARCHAR(64)     NOT NULL DEFAULT '',
    ai_value             TEXT            NOT NULL DEFAULT '',
    nurse_value          TEXT            NOT NULL DEFAULT '',
    same_flag            SMALLINT        NOT NULL DEFAULT 0,
    difference_type      VARCHAR(64)     NOT NULL DEFAULT '',
    difference_reason    VARCHAR(1000)   NOT NULL DEFAULT '',
    creator              VARCHAR(64)     NOT NULL DEFAULT '',
    updator              VARCHAR(64)     NOT NULL DEFAULT '',
    create_time          TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time          TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted              SMALLINT        NOT NULL DEFAULT 0
);
COMMENT ON TABLE  assessment_comparison_item IS '人机对比明细（按题目或评分项）';
COMMENT ON COLUMN assessment_comparison_item.compare_object_type IS 'question_answer / component_score / total_score / risk_level';
COMMENT ON COLUMN assessment_comparison_item.difference_type     IS 'missed / misjudged / score_error / incomplete_info';
CREATE INDEX ix_comparison_item_cmp ON assessment_comparison_item (comparison_id);
