-- ============================================================
-- 05_quality_review.sql  --  护士对 AI 的质量评价域
-- 表: quality_review_template, quality_review_dimension,
--     quality_review, quality_review_score
-- ============================================================

-- ----------------------------
-- 1. quality_review_template  质量评分模板
-- ----------------------------
CREATE TABLE quality_review_template (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(64)  NOT NULL,
    template_name VARCHAR(128) NOT NULL,
    target_type   VARCHAR(32)  NOT NULL,
    score_scale   VARCHAR(32)  NOT NULL DEFAULT '0-100',
    version_code  VARCHAR(64)  NOT NULL DEFAULT 'v1',
    status        VARCHAR(32)  NOT NULL DEFAULT 'enabled',
    creator       VARCHAR(64)  NOT NULL DEFAULT '',
    updator       VARCHAR(64)  NOT NULL DEFAULT '',
    create_time   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  quality_review_template IS 'AI 对话质量/AI 评估质量可使用不同模板；维度不硬编码为列';
COMMENT ON COLUMN quality_review_template.target_type IS 'ai_dialogue / ai_assessment';
CREATE UNIQUE INDEX ux_quality_tmpl_code ON quality_review_template (template_code, version_code) WHERE deleted = 0;

-- ----------------------------
-- 2. quality_review_dimension  质量评分维度
-- ----------------------------
CREATE TABLE quality_review_dimension (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id           BIGINT          NOT NULL,
    dimension_code        VARCHAR(64)     NOT NULL,
    dimension_name        VARCHAR(128)    NOT NULL,
    dimension_description VARCHAR(500)    NOT NULL DEFAULT '',
    weight                NUMERIC(5,2)    NOT NULL DEFAULT 1.00,
    max_score             NUMERIC(10,2)   NOT NULL DEFAULT 100,
    sort_no               INTEGER         NOT NULL DEFAULT 0,
    creator               VARCHAR(64)     NOT NULL DEFAULT '',
    updator               VARCHAR(64)     NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT        NOT NULL DEFAULT 0
);
COMMENT ON TABLE quality_review_dimension IS '质量评分维度（CICARE规范性/信息准确性/追问合理性/答案完整性等）';
CREATE UNIQUE INDEX ux_quality_dim_code ON quality_review_dimension (template_id, dimension_code) WHERE deleted = 0;
CREATE        INDEX ix_quality_dim_tmpl ON quality_review_dimension (template_id);

-- ----------------------------
-- 3. quality_review  护士质量评价记录
-- ----------------------------
CREATE TABLE quality_review (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_no    VARCHAR(64)  NOT NULL,
    template_id  BIGINT       NOT NULL,
    target_type  VARCHAR(32)  NOT NULL,
    target_id    BIGINT       NOT NULL,
    patient_id   BIGINT       NOT NULL,
    encounter_id BIGINT       NOT NULL,
    reviewer_id  BIGINT       NOT NULL,
    overall_score NUMERIC(10,2),
    review_comment TEXT       NOT NULL DEFAULT '',
    issue_tags   JSONB        NOT NULL DEFAULT '[]'::JSONB,
    reviewed_at  TIMESTAMP(3),
    creator      VARCHAR(64)  NOT NULL DEFAULT '',
    updator      VARCHAR(64)  NOT NULL DEFAULT '',
    create_time  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  quality_review IS '护士对某次 AI 对话或 AI 评估的总体评价';
COMMENT ON COLUMN quality_review.target_type IS 'ai_dialogue(target_id=interaction_session.id) / ai_assessment(target_id=assessment_submission.id)';
CREATE UNIQUE INDEX ux_quality_review_no  ON quality_review (review_no) WHERE deleted = 0;
CREATE        INDEX ix_quality_review_target ON quality_review (target_type, target_id);

-- ----------------------------
-- 4. quality_review_score  质量评价分项
-- ----------------------------
CREATE TABLE quality_review_score (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quality_review_id    BIGINT          NOT NULL,
    dimension_id         BIGINT          NOT NULL,
    score_value          NUMERIC(10,2),
    score_comment        TEXT            NOT NULL DEFAULT '',
    evidence_message_ids JSONB           NOT NULL DEFAULT '[]'::JSONB,
    evidence_question_ids JSONB          NOT NULL DEFAULT '[]'::JSONB,
    creator              VARCHAR(64)     NOT NULL DEFAULT '',
    updator              VARCHAR(64)     NOT NULL DEFAULT '',
    create_time          TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time          TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted              SMALLINT        NOT NULL DEFAULT 0
);
COMMENT ON TABLE  quality_review_score IS '质量评价分项得分；对话/评估质量统一复用此两张表，模板不同';
CREATE UNIQUE INDEX ux_qr_score_dim ON quality_review_score (quality_review_id, dimension_id) WHERE deleted = 0;
CREATE        INDEX ix_qr_score_review ON quality_review_score (quality_review_id);
