-- ============================================================
-- 06_content_delivery.sql  --  通用 AI 内容播报域
-- 表: content_delivery_session, content_delivery_item,
--     content_playback_event
-- ============================================================

-- ----------------------------
-- 1. content_delivery_session  内容播报会话
-- ----------------------------
CREATE TABLE content_delivery_session (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_no            VARCHAR(64)  NOT NULL,
    task_id                BIGINT       NOT NULL,
    patient_id             BIGINT       NOT NULL,
    encounter_id           BIGINT       NOT NULL,
    business_type          VARCHAR(32)  NOT NULL,
    business_id            BIGINT       NOT NULL,
    interaction_session_id BIGINT       NOT NULL DEFAULT 0,
    participant_type       VARCHAR(32)  NOT NULL DEFAULT 'patient',
    delivery_channel       VARCHAR(32)  NOT NULL DEFAULT 'text',
    tts_provider           VARCHAR(64)  NOT NULL DEFAULT '',
    tts_model              VARCHAR(64)  NOT NULL DEFAULT '',
    voice_name             VARCHAR(64)  NOT NULL DEFAULT '',
    language_code          VARCHAR(32)  NOT NULL DEFAULT 'zh_CN',
    speech_rate            NUMERIC(5,2) NOT NULL DEFAULT 1.00,
    delivery_status        VARCHAR(32)  NOT NULL DEFAULT 'pending',
    started_at             TIMESTAMP(3),
    completed_at           TIMESTAMP(3),
    planned_duration_ms    INTEGER      NOT NULL DEFAULT 0,
    actual_duration_ms     INTEGER      NOT NULL DEFAULT 0,
    completion_rate        NUMERIC(5,2) NOT NULL DEFAULT 0,
    handoff_required       SMALLINT     NOT NULL DEFAULT 0,
    handoff_reason         VARCHAR(500) NOT NULL DEFAULT '',
    creator                VARCHAR(64)  NOT NULL DEFAULT '',
    updator                VARCHAR(64)  NOT NULL DEFAULT '',
    create_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  content_delivery_session IS 'AI 向患者/家属播报宣教或知情同意内容的完整播报过程；同一记录可多次播报';
COMMENT ON COLUMN content_delivery_session.business_type IS 'admission_education / discharge_education / medical_education / consent';
COMMENT ON COLUMN content_delivery_session.business_id   IS 'education_record.id 或 consent_record.id';
COMMENT ON COLUMN content_delivery_session.delivery_channel IS 'text / ai_voice / pre_recorded / nurse';
COMMENT ON COLUMN content_delivery_session.delivery_status IS 'pending / delivering / paused / completed / interrupted / handoff';
CREATE UNIQUE INDEX ux_delivery_no       ON content_delivery_session (delivery_no) WHERE deleted = 0;
CREATE        INDEX ix_delivery_task     ON content_delivery_session (task_id);
CREATE        INDEX ix_delivery_business ON content_delivery_session (business_type, business_id);

-- ----------------------------
-- 2. content_delivery_item  播报内容明细
-- ----------------------------
CREATE TABLE content_delivery_item (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_session_id   BIGINT          NOT NULL,
    source_type           VARCHAR(32)     NOT NULL,
    source_id             BIGINT          NOT NULL,
    sequence_no           INTEGER         NOT NULL DEFAULT 0,
    mandatory             SMALLINT        NOT NULL DEFAULT 0,
    selected_reason       VARCHAR(64)     NOT NULL DEFAULT '',
    original_text_snapshot  TEXT          NOT NULL DEFAULT '',
    patient_text_snapshot   TEXT          NOT NULL DEFAULT '',
    spoken_text_snapshot    TEXT          NOT NULL DEFAULT '',
    audio_url             VARCHAR(512)    NOT NULL DEFAULT '',
    audio_duration_ms     INTEGER         NOT NULL DEFAULT 0,
    delivery_status       VARCHAR(32)     NOT NULL DEFAULT 'pending',
    started_at            TIMESTAMP(3),
    completed_at          TIMESTAMP(3),
    listened_duration_ms  INTEGER         NOT NULL DEFAULT 0,
    completion_rate       NUMERIC(5,2)    NOT NULL DEFAULT 0,
    replay_count          INTEGER         NOT NULL DEFAULT 0,
    patient_acknowledged  SMALLINT        NOT NULL DEFAULT 0,
    creator               VARCHAR(64)     NOT NULL DEFAULT '',
    updator               VARCHAR(64)     NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT        NOT NULL DEFAULT 0
);
COMMENT ON TABLE  content_delivery_item IS '播报会话实际计划和播报的每个内容单元；必须保存播报快照而非仅引用模板';
COMMENT ON COLUMN content_delivery_item.source_type     IS 'education_unit / consent_clause';
COMMENT ON COLUMN content_delivery_item.selected_reason IS 'mandatory / disease_match / surgery_match / drug_match / risk_triggered / nurse_selected';
COMMENT ON COLUMN content_delivery_item.delivery_status IS 'pending / delivering / completed / skipped / interrupted';
CREATE INDEX ix_delivery_item_session ON content_delivery_item (delivery_session_id, sequence_no);

-- ----------------------------
-- 3. content_playback_event  播放操作事件
-- ----------------------------
CREATE TABLE content_playback_event (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_session_id BIGINT       NOT NULL,
    delivery_item_id    BIGINT       NOT NULL DEFAULT 0,
    event_type          VARCHAR(32)  NOT NULL,
    position_ms         INTEGER      NOT NULL DEFAULT 0,
    event_time          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_source        VARCHAR(32)  NOT NULL DEFAULT 'patient',
    device_info         VARCHAR(255) NOT NULL DEFAULT '',
    failure_reason      VARCHAR(255) NOT NULL DEFAULT '',
    creator             VARCHAR(64)  NOT NULL DEFAULT '',
    updator             VARCHAR(64)  NOT NULL DEFAULT '',
    create_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  content_playback_event IS '患者播放/暂停/跳过/重听等行为事件；证明内容是否实际播放';
COMMENT ON COLUMN content_playback_event.event_type   IS 'start / pause / resume / skip / replay / complete / failure';
COMMENT ON COLUMN content_playback_event.event_source IS 'patient / ai / nurse / system';
CREATE INDEX ix_playback_event_session ON content_playback_event (delivery_session_id);
CREATE INDEX ix_playback_event_item    ON content_playback_event (delivery_item_id)   WHERE delivery_item_id > 0;
