-- ============================================================
-- 07a_education_template.sql  --  宣教模板域
-- 表: education_program, education_program_version,
--     education_unit, education_selection_rule,
--     medication_education_knowledge
-- ============================================================

-- ----------------------------
-- 1. education_program  宣教方案主档
-- ----------------------------
CREATE TABLE education_program (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_code            VARCHAR(64)  NOT NULL,
    program_name            VARCHAR(128) NOT NULL,
    education_stage         VARCHAR(32)  NOT NULL,
    program_type            VARCHAR(32)  NOT NULL,
    applicable_department   VARCHAR(256) NOT NULL DEFAULT '',
    applicable_disease_tags JSONB        NOT NULL DEFAULT '[]'::JSONB,
    source_file             VARCHAR(512) NOT NULL DEFAULT '',
    status                  VARCHAR(32)  NOT NULL DEFAULT 'draft',
    creator                 VARCHAR(64)  NOT NULL DEFAULT '',
    updator                 VARCHAR(64)  NOT NULL DEFAULT '',
    create_time             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                 SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  education_program IS '宣教方案主档（心内科入院宣教/冠心病出院宣教/PCI术后宣教等）';
COMMENT ON COLUMN education_program.education_stage IS 'admission / in_hospital / discharge';
COMMENT ON COLUMN education_program.program_type    IS 'routine / nursing_safety / medical_knowledge / disease_specific / drug_specific';
CREATE UNIQUE INDEX ux_edu_program_code ON education_program (program_code) WHERE deleted = 0;

-- ----------------------------
-- 2. education_program_version  宣教方案版本
-- ----------------------------
CREATE TABLE education_program_version (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id       BIGINT       NOT NULL,
    version_code     VARCHAR(64)  NOT NULL,
    publish_status   VARCHAR(32)  NOT NULL DEFAULT 'draft',
    effective_time   TIMESTAMP(3),
    expire_time      TIMESTAMP(3),
    content_snapshot JSONB        NOT NULL DEFAULT '{}'::JSONB,
    content_hash     VARCHAR(128) NOT NULL DEFAULT '',
    creator          VARCHAR(64)  NOT NULL DEFAULT '',
    updator          VARCHAR(64)  NOT NULL DEFAULT '',
    create_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted          SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  education_program_version IS '宣教方案可执行版本；出诊时间/联系电话等易变内容通过新版本更新';
CREATE UNIQUE INDEX ux_edu_version_code ON education_program_version (program_id, version_code) WHERE deleted = 0;
CREATE        INDEX ix_edu_version_prog ON education_program_version (program_id);

-- ----------------------------
-- 3. education_unit  宣教内容单元
-- ----------------------------
CREATE TABLE education_unit (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_version_id BIGINT       NOT NULL,
    parent_unit_id     BIGINT       NOT NULL DEFAULT 0,
    unit_code          VARCHAR(64)  NOT NULL,
    unit_title         VARCHAR(128) NOT NULL,
    unit_type          VARCHAR(64)  NOT NULL,
    original_text      TEXT         NOT NULL DEFAULT '',
    patient_text       TEXT         NOT NULL DEFAULT '',
    voice_text         TEXT         NOT NULL DEFAULT '',
    mandatory          SMALLINT     NOT NULL DEFAULT 0,
    teachback_required SMALLINT     NOT NULL DEFAULT 0,
    risk_level         VARCHAR(32)  NOT NULL DEFAULT 'normal',
    sort_no            INTEGER      NOT NULL DEFAULT 0,
    creator            VARCHAR(64)  NOT NULL DEFAULT '',
    updator            VARCHAR(64)  NOT NULL DEFAULT '',
    create_time        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted            SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  education_unit IS '可选择/播报/追踪的最小宣教内容单元';
COMMENT ON COLUMN education_unit.unit_type  IS 'environment_intro/process_guide/medication/diet/activity/follow_up/risk_warning/vte';
COMMENT ON COLUMN education_unit.risk_level IS 'normal / important / high_risk';
CREATE UNIQUE INDEX ux_edu_unit_code    ON education_unit (program_version_id, unit_code) WHERE deleted = 0;
CREATE        INDEX ix_edu_unit_version ON education_unit (program_version_id);

-- ----------------------------
-- 4. education_selection_rule  宣教内容选择规则
-- ----------------------------
CREATE TABLE education_selection_rule (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_version_id BIGINT       NOT NULL,
    unit_id            BIGINT       NOT NULL,
    condition_type     VARCHAR(32)  NOT NULL,
    condition_expression VARCHAR(500) NOT NULL DEFAULT '',
    selection_result   VARCHAR(32)  NOT NULL DEFAULT 'auto_include',
    priority           INTEGER      NOT NULL DEFAULT 0,
    creator            VARCHAR(64)  NOT NULL DEFAULT '',
    updator            VARCHAR(64)  NOT NULL DEFAULT '',
    create_time        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted            SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  education_selection_rule IS '根据患者病种/手术/药物/量表风险决定本次需宣教哪些单元';
COMMENT ON COLUMN education_selection_rule.condition_type   IS 'disease / surgery / medication / assessment_result / age / department';
COMMENT ON COLUMN education_selection_rule.selection_result IS 'auto_include / recommend / exclude';
CREATE INDEX ix_edu_sel_rule_version ON education_selection_rule (program_version_id);
CREATE INDEX ix_edu_sel_rule_unit    ON education_selection_rule (unit_id);

-- ----------------------------
-- 5. medication_education_knowledge  药物宣教知识库
-- ----------------------------
CREATE TABLE medication_education_knowledge (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_code             VARCHAR(64)  NOT NULL,
    generic_name          VARCHAR(128) NOT NULL,
    brand_name            VARCHAR(128) NOT NULL DEFAULT '',
    drug_category         VARCHAR(64)  NOT NULL DEFAULT '',
    purpose_text          TEXT         NOT NULL DEFAULT '',
    administration_text   TEXT         NOT NULL DEFAULT '',
    warning_text          TEXT         NOT NULL DEFAULT '',
    adverse_reaction_text TEXT         NOT NULL DEFAULT '',
    emergency_text        TEXT         NOT NULL DEFAULT '',
    teachback_required    SMALLINT     NOT NULL DEFAULT 0,
    version_code          VARCHAR(64)  NOT NULL DEFAULT 'v1',
    status                VARCHAR(32)  NOT NULL DEFAULT 'enabled',
    creator               VARCHAR(64)  NOT NULL DEFAULT '',
    updator               VARCHAR(64)  NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  medication_education_knowledge IS '经审核的药物宣教知识；AI 只播报患者实际使用的药物';
COMMENT ON COLUMN medication_education_knowledge.drug_category IS 'anticoagulant / antiplatelet / statin / antihypertensive / hypoglycemic 等';
CREATE UNIQUE INDEX ux_med_knowledge_code ON medication_education_knowledge (drug_code, version_code) WHERE deleted = 0;
