-- ============================================================
-- 07b_education_run.sql  --  宣教运行域
-- 表: education_record, education_record_item,
--     teachback_question, teachback_attempt,
--     education_signature, patient_medication_education,
--     follow_up_plan, follow_up_plan_item
-- ============================================================

-- ----------------------------
-- 1. education_record  患者宣教主记录
-- ----------------------------
CREATE TABLE education_record (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no           VARCHAR(64)  NOT NULL,
    task_id             BIGINT       NOT NULL,
    patient_id          BIGINT       NOT NULL,
    encounter_id        BIGINT       NOT NULL,
    program_id          BIGINT       NOT NULL,
    program_version_id  BIGINT       NOT NULL,
    education_stage     VARCHAR(32)  NOT NULL,
    participant_type    VARCHAR(32)  NOT NULL DEFAULT 'patient',
    record_status       VARCHAR(32)  NOT NULL DEFAULT 'pending',
    selection_snapshot  JSONB        NOT NULL DEFAULT '{}'::JSONB,
    started_at          TIMESTAMP(3),
    completed_at        TIMESTAMP(3),
    overall_understanding VARCHAR(32) NOT NULL DEFAULT 'unconfirmed',
    need_nurse_follow_up SMALLINT    NOT NULL DEFAULT 0,
    nurse_confirmed_by  BIGINT       NOT NULL DEFAULT 0,
    nurse_confirmed_at  TIMESTAMP(3),
    creator             VARCHAR(64)  NOT NULL DEFAULT '',
    updator             VARCHAR(64)  NOT NULL DEFAULT '',
    create_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  education_record IS '患者某次住院接受某宣教方案的业务记录';
COMMENT ON COLUMN education_record.record_status        IS 'pending / in_progress / pending_teachback / pending_nurse_confirm / completed / interrupted';
COMMENT ON COLUMN education_record.overall_understanding IS 'unconfirmed / understood / partial / not_understood';
CREATE UNIQUE INDEX ux_education_record_no  ON education_record (record_no) WHERE deleted = 0;
CREATE        INDEX ix_education_record_task ON education_record (task_id);
CREATE        INDEX ix_education_record_pat  ON education_record (patient_id, encounter_id);

-- ----------------------------
-- 2. education_record_item  患者宣教项目
-- ----------------------------
CREATE TABLE education_record_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_record_id BIGINT       NOT NULL,
    education_unit_id   BIGINT       NOT NULL,
    delivery_item_id    BIGINT       NOT NULL DEFAULT 0,
    selection_source    VARCHAR(32)  NOT NULL DEFAULT 'auto_rule',
    selection_reason    VARCHAR(500) NOT NULL DEFAULT '',
    required            SMALLINT     NOT NULL DEFAULT 0,
    education_status    VARCHAR(32)  NOT NULL DEFAULT 'pending',
    patient_acknowledged SMALLINT    NOT NULL DEFAULT 0,
    understanding_status VARCHAR(32) NOT NULL DEFAULT 'unconfirmed',
    teachback_required  SMALLINT     NOT NULL DEFAULT 0,
    nurse_comment       VARCHAR(500) NOT NULL DEFAULT '',
    creator             VARCHAR(64)  NOT NULL DEFAULT '',
    updator             VARCHAR(64)  NOT NULL DEFAULT '',
    create_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  education_record_item IS 'VTE 17 项/出院健教勾选项等逐项保存，不能只存"已完成"';
COMMENT ON COLUMN education_record_item.selection_source IS 'auto_rule / ai_recommended / nurse_selected';
COMMENT ON COLUMN education_record_item.education_status IS 'pending / delivered / skipped / need_nurse';
CREATE INDEX ix_edu_record_item_record ON education_record_item (education_record_id);

-- ----------------------------
-- 3. teachback_question  Teach-back 问题
-- ----------------------------
CREATE TABLE teachback_question (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_unit_id BIGINT       NOT NULL,
    question_code     VARCHAR(64)  NOT NULL,
    question_text     TEXT         NOT NULL,
    standard_answer   TEXT         NOT NULL DEFAULT '',
    pass_rule         JSONB        NOT NULL DEFAULT '{}'::JSONB,
    max_attempts      INTEGER      NOT NULL DEFAULT 3,
    status            VARCHAR(32)  NOT NULL DEFAULT 'enabled',
    creator           VARCHAR(64)  NOT NULL DEFAULT '',
    updator           VARCHAR(64)  NOT NULL DEFAULT '',
    create_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE teachback_question IS '宣教单元对应的 Teach-back 反问问题和判定规则';
CREATE UNIQUE INDEX ux_teachback_q_code ON teachback_question (education_unit_id, question_code) WHERE deleted = 0;
CREATE        INDEX ix_teachback_q_unit ON teachback_question (education_unit_id);

-- ----------------------------
-- 4. teachback_attempt  Teach-back 回答记录
-- ----------------------------
CREATE TABLE teachback_attempt (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_record_item_id BIGINT       NOT NULL,
    question_id              BIGINT       NOT NULL,
    interaction_message_id   BIGINT       NOT NULL DEFAULT 0,
    attempt_no               INTEGER      NOT NULL DEFAULT 1,
    patient_answer           TEXT         NOT NULL DEFAULT '',
    judge_source             VARCHAR(32)  NOT NULL DEFAULT 'ai',
    judge_result             VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    judge_reason             VARCHAR(500) NOT NULL DEFAULT '',
    need_nurse_follow_up     SMALLINT     NOT NULL DEFAULT 0,
    creator                  VARCHAR(64)  NOT NULL DEFAULT '',
    updator                  VARCHAR(64)  NOT NULL DEFAULT '',
    create_time              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                  SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  teachback_attempt IS '患者每次 Teach-back 回答及判定；两次未通过建议转人工';
COMMENT ON COLUMN teachback_attempt.judge_source IS 'ai / nurse';
COMMENT ON COLUMN teachback_attempt.judge_result IS 'pass / fail / uncertain / unknown';
CREATE INDEX ix_teachback_attempt_item ON teachback_attempt (education_record_item_id);

-- ----------------------------
-- 5. education_signature  宣教签名
-- ----------------------------
CREATE TABLE education_signature (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_record_id BIGINT       NOT NULL,
    signer_type         VARCHAR(32)  NOT NULL,
    signer_id           BIGINT       NOT NULL DEFAULT 0,
    signer_name_snapshot VARCHAR(128) NOT NULL DEFAULT '',
    signature_method    VARCHAR(32)  NOT NULL DEFAULT 'account_confirm',
    signature_file_url  VARCHAR(512) NOT NULL DEFAULT '',
    signed_at           TIMESTAMP(3),
    creator             VARCHAR(64)  NOT NULL DEFAULT '',
    updator             VARCHAR(64)  NOT NULL DEFAULT '',
    create_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  education_signature IS 'VTE/出院健教等护士和患者签名';
COMMENT ON COLUMN education_signature.signer_type      IS 'nurse / patient / family';
COMMENT ON COLUMN education_signature.signature_method IS 'account_confirm / handwritten / electronic / paper_record';
CREATE INDEX ix_edu_signature_record ON education_signature (education_record_id);

-- ----------------------------
-- 6. patient_medication_education  患者用药宣教明细
-- ----------------------------
CREATE TABLE patient_medication_education (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_record_id     BIGINT       NOT NULL,
    medication_knowledge_id BIGINT       NOT NULL,
    medication_order_id     BIGINT       NOT NULL DEFAULT 0,
    drug_name_snapshot      VARCHAR(128) NOT NULL DEFAULT '',
    dose_snapshot           VARCHAR(64)  NOT NULL DEFAULT '',
    frequency_snapshot      VARCHAR(64)  NOT NULL DEFAULT '',
    route_snapshot          VARCHAR(64)  NOT NULL DEFAULT '',
    duration_snapshot       VARCHAR(64)  NOT NULL DEFAULT '',
    warning_snapshot        TEXT         NOT NULL DEFAULT '',
    delivery_item_id        BIGINT       NOT NULL DEFAULT 0,
    understanding_status    VARCHAR(32)  NOT NULL DEFAULT 'unconfirmed',
    teachback_result        VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    nurse_confirmed         SMALLINT     NOT NULL DEFAULT 0,
    creator                 VARCHAR(64)  NOT NULL DEFAULT '',
    updator                 VARCHAR(64)  NOT NULL DEFAULT '',
    create_time             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                 SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  patient_medication_education IS '药物宣教单勾选的每种药物形成一条记录；不能仅保存药物类别';
COMMENT ON COLUMN patient_medication_education.medication_order_id IS '院内医嘱/出院带药 ID，可选';
CREATE INDEX ix_pat_med_edu_record ON patient_medication_education (education_record_id);

-- ----------------------------
-- 7. follow_up_plan  出院后复诊随访计划
-- ----------------------------
CREATE TABLE follow_up_plan (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_no             VARCHAR(64)  NOT NULL,
    patient_id          BIGINT       NOT NULL,
    encounter_id        BIGINT       NOT NULL,
    education_record_id BIGINT       NOT NULL DEFAULT 0,
    plan_status         VARCHAR(32)  NOT NULL DEFAULT 'draft',
    confirmed_by        BIGINT       NOT NULL DEFAULT 0,
    confirmed_at        TIMESTAMP(3),
    creator             VARCHAR(64)  NOT NULL DEFAULT '',
    updator             VARCHAR(64)  NOT NULL DEFAULT '',
    create_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  follow_up_plan IS '出院复诊及随访总计划';
COMMENT ON COLUMN follow_up_plan.plan_status IS 'draft / pending_confirm / confirmed / ended';
CREATE UNIQUE INDEX ux_follow_up_plan_no  ON follow_up_plan (plan_no) WHERE deleted = 0;
CREATE        INDEX ix_follow_up_plan_pat ON follow_up_plan (patient_id, encounter_id);

-- ----------------------------
-- 8. follow_up_plan_item  复诊随访计划项
-- ----------------------------
CREATE TABLE follow_up_plan_item (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follow_up_plan_id BIGINT       NOT NULL,
    item_type         VARCHAR(32)  NOT NULL,
    planned_date      DATE,
    time_offset_value INTEGER,
    time_offset_unit  VARCHAR(16)  NOT NULL DEFAULT '',
    department_name   VARCHAR(128) NOT NULL DEFAULT '',
    location_text     VARCHAR(255) NOT NULL DEFAULT '',
    contact_text      VARCHAR(255) NOT NULL DEFAULT '',
    preparation_text  TEXT         NOT NULL DEFAULT '',
    status            VARCHAR(32)  NOT NULL DEFAULT 'pending',
    completed_at      TIMESTAMP(3),
    creator           VARCHAR(64)  NOT NULL DEFAULT '',
    updator           VARCHAR(64)  NOT NULL DEFAULT '',
    create_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  follow_up_plan_item IS 'PCI 术后1/3/6/12月复诊各为一条；微信随访/电话随访同理';
COMMENT ON COLUMN follow_up_plan_item.item_type        IS 'outpatient_visit / wechat_followup / phone_followup / checkup';
COMMENT ON COLUMN follow_up_plan_item.time_offset_unit IS 'day / week / month';
COMMENT ON COLUMN follow_up_plan_item.status           IS 'pending / completed / cancelled / lost_to_follow_up';
CREATE INDEX ix_follow_up_item_plan ON follow_up_plan_item (follow_up_plan_id);
