-- ============================================================
-- 08a_consent_template.sql  --  知情同意模板域
-- 表: consent_document, consent_document_version,
--     consent_clause, consent_item_definition
-- ============================================================

-- ----------------------------
-- 1. consent_document  知情同意书主档
-- ----------------------------
CREATE TABLE consent_document (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code     VARCHAR(64)  NOT NULL,
    document_name     VARCHAR(255) NOT NULL,
    document_type     VARCHAR(64)  NOT NULL,
    applicable_scope  VARCHAR(255) NOT NULL DEFAULT '',
    dept_scope        VARCHAR(255) NOT NULL DEFAULT '',
    legal_basis       VARCHAR(500) NOT NULL DEFAULT '',
    requires_witness  SMALLINT     NOT NULL DEFAULT 0,
    status            VARCHAR(32)  NOT NULL DEFAULT 'draft',
    creator           VARCHAR(64)  NOT NULL DEFAULT '',
    updator           VARCHAR(64)  NOT NULL DEFAULT '',
    create_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_document IS '知情同意书主档（手术同意书/麻醉同意书/侵入性操作同意书/输血同意书等）';
COMMENT ON COLUMN consent_document.document_type IS 'surgery / anesthesia / invasive_procedure / blood_transfusion / special_medication / discharge_against_advice / research';
CREATE UNIQUE INDEX ux_consent_doc_code ON consent_document (document_code) WHERE deleted = 0;

-- ----------------------------
-- 2. consent_document_version  知情同意书版本
-- ----------------------------
CREATE TABLE consent_document_version (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id       BIGINT       NOT NULL,
    version_code      VARCHAR(32)  NOT NULL,
    version_name      VARCHAR(128) NOT NULL DEFAULT '',
    publish_status    VARCHAR(32)  NOT NULL DEFAULT 'draft',
    effective_date    DATE,
    expire_date       DATE,
    content_snapshot  JSONB        NOT NULL DEFAULT '{}'::JSONB,
    content_hash      VARCHAR(128) NOT NULL DEFAULT '',
    creator           VARCHAR(64)  NOT NULL DEFAULT '',
    updator           VARCHAR(64)  NOT NULL DEFAULT '',
    create_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_document_version IS '每次修订产生新版本；content_snapshot 冻结全量条款快照';
COMMENT ON COLUMN consent_document_version.publish_status IS 'draft / published / deprecated';
CREATE UNIQUE INDEX ux_consent_doc_ver ON consent_document_version (document_id, version_code) WHERE deleted = 0;
CREATE        INDEX ix_consent_doc_ver_doc ON consent_document_version (document_id);

-- ----------------------------
-- 3. consent_clause  知情同意条款
-- ----------------------------
CREATE TABLE consent_clause (
    id                           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id          BIGINT        NOT NULL,
    clause_code                  VARCHAR(64)   NOT NULL,
    clause_name                  VARCHAR(255)  NOT NULL DEFAULT '',
    clause_type                  VARCHAR(64)   NOT NULL,
    sequence_no                  INTEGER       NOT NULL DEFAULT 0,
    original_content             TEXT          NOT NULL DEFAULT '',
    patient_content              TEXT          NOT NULL DEFAULT '',
    voice_content                TEXT          NOT NULL DEFAULT '',
    importance_level             VARCHAR(32)   NOT NULL DEFAULT 'normal',
    mandatory_delivery           SMALLINT      NOT NULL DEFAULT 1,
    explicit_confirmation_required SMALLINT    NOT NULL DEFAULT 0,
    teachback_required           SMALLINT      NOT NULL DEFAULT 0,
    display_condition            JSONB         NOT NULL DEFAULT '{}'::JSONB,
    creator                      VARCHAR(64)   NOT NULL DEFAULT '',
    updator                      VARCHAR(64)   NOT NULL DEFAULT '',
    create_time                  TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                  TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                      SMALLINT      NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_clause IS '知情同意条款；一个版本含多条；voice_content 为 TTS 播报文本';
COMMENT ON COLUMN consent_clause.clause_type       IS 'risk_disclosure / benefit_statement / alternative_statement / patient_right / special_note / signature_statement';
COMMENT ON COLUMN consent_clause.importance_level  IS 'normal / important / critical';
COMMENT ON COLUMN consent_clause.display_condition IS '动态显示条件，空对象表示始终显示';
CREATE UNIQUE INDEX ux_consent_clause_code ON consent_clause (document_version_id, clause_code) WHERE deleted = 0;
CREATE        INDEX ix_consent_clause_ver  ON consent_clause (document_version_id);

-- ----------------------------
-- 4. consent_item_definition  知情同意签署项定义（患者需明确选择/确认的选项）
-- ----------------------------
CREATE TABLE consent_item_definition (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id BIGINT       NOT NULL,
    clause_id           BIGINT       NOT NULL DEFAULT 0,
    item_code           VARCHAR(64)  NOT NULL,
    item_label          VARCHAR(255) NOT NULL DEFAULT '',
    item_type           VARCHAR(32)  NOT NULL,
    response_type       VARCHAR(32)  NOT NULL DEFAULT 'yes_no',
    required            SMALLINT     NOT NULL DEFAULT 1,
    sequence_no         INTEGER      NOT NULL DEFAULT 0,
    help_text           TEXT         NOT NULL DEFAULT '',
    creator             VARCHAR(64)  NOT NULL DEFAULT '',
    updator             VARCHAR(64)  NOT NULL DEFAULT '',
    create_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_item_definition IS '需患者/家属明确应答的签署项；如"是否同意手术""是否放弃抢救"';
COMMENT ON COLUMN consent_item_definition.item_type     IS 'consent / refusal / choice / acknowledgement';
COMMENT ON COLUMN consent_item_definition.response_type IS 'yes_no / single_choice / multi_choice / free_text';
CREATE UNIQUE INDEX ux_consent_item_code ON consent_item_definition (document_version_id, item_code) WHERE deleted = 0;
CREATE        INDEX ix_consent_item_ver  ON consent_item_definition (document_version_id);

