-- ============================================================
-- 08b_consent_run.sql  --  知情同意执行域
-- 表: consent_record, consent_clause_record, consent_record_item,
--     consent_participant, consent_authorization, consent_signature
-- ============================================================

-- ----------------------------
-- 1. consent_record  知情同意记录
-- ----------------------------
CREATE TABLE consent_record (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no           VARCHAR(64)  NOT NULL,
    patient_id          BIGINT       NOT NULL,
    encounter_id        BIGINT       NOT NULL,
    care_task_id        BIGINT       NOT NULL DEFAULT 0,
    document_id         BIGINT       NOT NULL,
    document_version_id BIGINT       NOT NULL,
    delivery_session_id BIGINT       NOT NULL DEFAULT 0,
    record_status       VARCHAR(32)  NOT NULL DEFAULT 'pending',
    overall_result      VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    consent_at          TIMESTAMP(3),
    revoked_at          TIMESTAMP(3),
    revoke_reason       TEXT         NOT NULL DEFAULT '',
    creator             VARCHAR(64)  NOT NULL DEFAULT '',
    updator             VARCHAR(64)  NOT NULL DEFAULT '',
    create_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_record IS '每次知情同意宣讲+签署流程生成一条记录';
COMMENT ON COLUMN consent_record.record_status IS 'pending / delivering / delivered / signing / signed / revoked / expired';
COMMENT ON COLUMN consent_record.overall_result IS 'unknown / agreed / refused / partial_refused / revoked';
CREATE UNIQUE INDEX ux_consent_record_no  ON consent_record (record_no) WHERE deleted = 0;
CREATE        INDEX ix_consent_record_pat ON consent_record (patient_id, encounter_id);

-- ----------------------------
-- 2. consent_clause_record  条款播报记录
-- ----------------------------
CREATE TABLE consent_clause_record (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_record_id BIGINT       NOT NULL,
    clause_id         BIGINT       NOT NULL,
    delivery_item_id  BIGINT       NOT NULL DEFAULT 0,
    delivery_status   VARCHAR(32)  NOT NULL DEFAULT 'pending',
    listened_flag     SMALLINT     NOT NULL DEFAULT 0,
    replay_count      INTEGER      NOT NULL DEFAULT 0,
    question_raised   SMALLINT     NOT NULL DEFAULT 0,
    nurse_note        TEXT         NOT NULL DEFAULT '',
    creator           VARCHAR(64)  NOT NULL DEFAULT '',
    updator           VARCHAR(64)  NOT NULL DEFAULT '',
    create_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_clause_record IS '每条条款播报/展示情况的追踪；与 content_delivery_item 关联';
COMMENT ON COLUMN consent_clause_record.delivery_status IS 'pending / delivering / delivered / skipped';
CREATE INDEX ix_consent_clause_rec_consent ON consent_clause_record (consent_record_id);

-- ----------------------------
-- 3. consent_record_item  知情同意签署项执行记录
-- ----------------------------
CREATE TABLE consent_record_item (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_record_id     BIGINT       NOT NULL,
    item_definition_id    BIGINT       NOT NULL,
    response_value        VARCHAR(255) NOT NULL DEFAULT '',
    response_text         TEXT         NOT NULL DEFAULT '',
    responded_by          BIGINT       NOT NULL DEFAULT 0,
    responded_at          TIMESTAMP(3),
    item_status           VARCHAR(32)  NOT NULL DEFAULT 'pending',
    creator               VARCHAR(64)  NOT NULL DEFAULT '',
    updator               VARCHAR(64)  NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_record_item IS '患者/家属对每个签署项的应答结果';
COMMENT ON COLUMN consent_record_item.item_status IS 'pending / responded / waived';
CREATE UNIQUE INDEX ux_consent_rec_item ON consent_record_item (consent_record_id, item_definition_id) WHERE deleted = 0;

-- ----------------------------
-- 4. consent_participant  知情同意参与人
-- ----------------------------
CREATE TABLE consent_participant (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_record_id     BIGINT       NOT NULL,
    participant_type      VARCHAR(32)  NOT NULL,
    participant_name      VARCHAR(128) NOT NULL DEFAULT '',
    relation_to_patient   VARCHAR(64)  NOT NULL DEFAULT '',
    civil_capacity_status VARCHAR(32)  NOT NULL DEFAULT 'full',
    authorization_required SMALLINT    NOT NULL DEFAULT 0,
    identity_no_ciphertext   VARCHAR(512) NOT NULL DEFAULT '',
    phone_ciphertext         VARCHAR(512) NOT NULL DEFAULT '',
    address_ciphertext       VARCHAR(512) NOT NULL DEFAULT '',
    present_flag          SMALLINT     NOT NULL DEFAULT 1,
    creator               VARCHAR(64)  NOT NULL DEFAULT '',
    updator               VARCHAR(64)  NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_participant IS '知情同意现场参与人（患者本人 / 法定代理人 / 委托代理人 / 见证人）';
COMMENT ON COLUMN consent_participant.participant_type      IS 'patient / legal_guardian / authorized_agent / witness / nurse';
COMMENT ON COLUMN consent_participant.civil_capacity_status IS 'full / limited / none';
CREATE INDEX ix_consent_participant_rec ON consent_participant (consent_record_id);

-- ----------------------------
-- 5. consent_authorization  授权委托书
-- ----------------------------
CREATE TABLE consent_authorization (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_record_id     BIGINT       NOT NULL,
    participant_id        BIGINT       NOT NULL,
    authorization_reason  TEXT         NOT NULL DEFAULT '',
    authorization_scope   TEXT         NOT NULL DEFAULT '',
    effective_start       TIMESTAMP(3),
    effective_end         TIMESTAMP(3),
    authorizer_name       VARCHAR(128) NOT NULL DEFAULT '',
    authorizer_id_ciphertext VARCHAR(512) NOT NULL DEFAULT '',
    agent_name            VARCHAR(128) NOT NULL DEFAULT '',
    agent_id_ciphertext   VARCHAR(512) NOT NULL DEFAULT '',
    document_url          VARCHAR(500) NOT NULL DEFAULT '',
    verified_by           BIGINT       NOT NULL DEFAULT 0,
    verified_at           TIMESTAMP(3),
    authorization_status  VARCHAR(32)  NOT NULL DEFAULT 'pending',
    creator               VARCHAR(64)  NOT NULL DEFAULT '',
    updator               VARCHAR(64)  NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_authorization IS '患者本人无法签署时由其委托人出具的授权委托书';
COMMENT ON COLUMN consent_authorization.authorization_status IS 'pending / verified / rejected / expired';
CREATE INDEX ix_consent_auth_rec ON consent_authorization (consent_record_id);

-- ----------------------------
-- 6. consent_signature  知情同意签名
-- ----------------------------
CREATE TABLE consent_signature (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_record_id     BIGINT       NOT NULL,
    participant_id        BIGINT       NOT NULL DEFAULT 0,
    sign_purpose          VARCHAR(64)  NOT NULL,
    signer_type           VARCHAR(32)  NOT NULL,
    signature_method      VARCHAR(32)  NOT NULL,
    signature_file_url    VARCHAR(500) NOT NULL DEFAULT '',
    fingerprint_file_url  VARCHAR(500) NOT NULL DEFAULT '',
    signed_content_hash   VARCHAR(128) NOT NULL DEFAULT '',
    signing_ip            VARCHAR(64)  NOT NULL DEFAULT '',
    signed_at             TIMESTAMP(3),
    invalidated_at        TIMESTAMP(3),
    invalidate_reason     TEXT         NOT NULL DEFAULT '',
    creator               VARCHAR(64)  NOT NULL DEFAULT '',
    updator               VARCHAR(64)  NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  consent_signature IS '知情同意全流程签名留存；支持多种签署方式并存';
COMMENT ON COLUMN consent_signature.sign_purpose     IS 'patient_consent / guardian_consent / witness / nurse_confirm / doctor_confirm';
COMMENT ON COLUMN consent_signature.signer_type      IS 'patient / guardian / authorized_agent / witness / nurse / doctor';
COMMENT ON COLUMN consent_signature.signature_method IS 'electronic_handwritten / account_confirm / fingerprint / paper_upload / sms_otp';
COMMENT ON COLUMN consent_signature.signed_content_hash IS 'SHA-256 of the document+items snapshot at signing time';
CREATE INDEX ix_consent_sig_rec ON consent_signature (consent_record_id);


