-- ============================================================
-- 09_nursing_audit.sql  --  护理计划 & 审计域
-- 表: patient_profile_snapshot, nursing_plan, nursing_plan_item,
--     template_approval, operation_audit_log
-- ============================================================

-- ----------------------------
-- 1. patient_profile_snapshot  患者能力/风险快照
-- ----------------------------
CREATE TABLE patient_profile_snapshot (
    id                        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_no               VARCHAR(64)  NOT NULL,
    patient_id                BIGINT       NOT NULL,
    encounter_id              BIGINT       NOT NULL,
    care_task_id              BIGINT       NOT NULL DEFAULT 0,
    source_submission_ids     JSONB        NOT NULL DEFAULT '[]'::JSONB,
    snapshot_at               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cooperation_level         VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    cognition_level           VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    self_care_level           VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    fall_risk_level           VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    pressure_injury_level     VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    nutrition_risk_level      VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    communication_level       VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    education_need_level      VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    pain_level                VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    vte_risk_level            VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    extra_levels              JSONB        NOT NULL DEFAULT '{}'::JSONB,
    creator                   VARCHAR(64)  NOT NULL DEFAULT '',
    updator                   VARCHAR(64)  NOT NULL DEFAULT '',
    create_time               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                   SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  patient_profile_snapshot IS '从多份评估提交聚合的患者综合能力/风险快照；source_submission_ids 记录来源';
COMMENT ON COLUMN patient_profile_snapshot.cooperation_level     IS 'good / fair / poor / unknown';
COMMENT ON COLUMN patient_profile_snapshot.cognition_level       IS 'normal / mild_impaired / moderate_impaired / severe_impaired / unknown';
COMMENT ON COLUMN patient_profile_snapshot.self_care_level       IS 'independent / minor_assist / moderate_assist / major_assist / total_care / unknown';
COMMENT ON COLUMN patient_profile_snapshot.fall_risk_level       IS 'low / medium / high / unknown';
COMMENT ON COLUMN patient_profile_snapshot.pressure_injury_level IS 'low / medium / high / very_high / unknown';
COMMENT ON COLUMN patient_profile_snapshot.nutrition_risk_level  IS 'none / low / medium / high / unknown';
COMMENT ON COLUMN patient_profile_snapshot.extra_levels          IS '其他自定义评估维度 {"key": "level"}';
CREATE UNIQUE INDEX ux_profile_snapshot_no  ON patient_profile_snapshot (snapshot_no) WHERE deleted = 0;
CREATE        INDEX ix_profile_snapshot_enc ON patient_profile_snapshot (patient_id, encounter_id);

-- ----------------------------
-- 2. nursing_plan  护理计划
-- ----------------------------
CREATE TABLE nursing_plan (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_no               VARCHAR(64)  NOT NULL,
    patient_id            BIGINT       NOT NULL,
    encounter_id          BIGINT       NOT NULL,
    care_task_id          BIGINT       NOT NULL DEFAULT 0,
    profile_snapshot_id   BIGINT       NOT NULL DEFAULT 0,
    assessment_instance_id BIGINT      NOT NULL DEFAULT 0,
    plan_status           VARCHAR(32)  NOT NULL DEFAULT 'ai_draft',
    confirmed_by          BIGINT       NOT NULL DEFAULT 0,
    confirmed_at          TIMESTAMP(3),
    adjusted_by           BIGINT       NOT NULL DEFAULT 0,
    adjusted_at           TIMESTAMP(3),
    adjust_reason         TEXT         NOT NULL DEFAULT '',
    risk_summary          TEXT         NOT NULL DEFAULT '',
    education_summary     TEXT         NOT NULL DEFAULT '',
    handover_summary      TEXT         NOT NULL DEFAULT '',
    creator               VARCHAR(64)  NOT NULL DEFAULT '',
    updator               VARCHAR(64)  NOT NULL DEFAULT '',
    create_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  nursing_plan IS 'AI 生成草稿 → 护士确认/调整 → 生效；未经护士确认的 ai_draft 不具法律效力';
COMMENT ON COLUMN nursing_plan.plan_status IS 'ai_draft / pending_nurse_confirm / confirmed / adjusted / ended';
CREATE UNIQUE INDEX ux_nursing_plan_no  ON nursing_plan (plan_no) WHERE deleted = 0;
CREATE        INDEX ix_nursing_plan_enc ON nursing_plan (patient_id, encounter_id);

-- ----------------------------
-- 3. nursing_plan_item  护理计划项
-- ----------------------------
CREATE TABLE nursing_plan_item (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nursing_plan_id BIGINT       NOT NULL,
    item_type       VARCHAR(64)  NOT NULL,
    item_code       VARCHAR(64)  NOT NULL DEFAULT '',
    item_name       VARCHAR(255) NOT NULL DEFAULT '',
    item_content    TEXT         NOT NULL DEFAULT '',
    source_type     VARCHAR(64)  NOT NULL DEFAULT '',
    source_id       BIGINT       NOT NULL DEFAULT 0,
    priority        VARCHAR(32)  NOT NULL DEFAULT 'normal',
    frequency       VARCHAR(128) NOT NULL DEFAULT '',
    start_date      DATE,
    end_date        DATE,
    nurse_action    VARCHAR(32)  NOT NULL DEFAULT 'accept',
    nurse_note      TEXT         NOT NULL DEFAULT '',
    sequence_no     INTEGER      NOT NULL DEFAULT 0,
    creator         VARCHAR(64)  NOT NULL DEFAULT '',
    updator         VARCHAR(64)  NOT NULL DEFAULT '',
    create_time     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  nursing_plan_item IS '护理计划每一条措施；来源可以是评估规则/AI建议/护士手动添加';
COMMENT ON COLUMN nursing_plan_item.item_type    IS 'risk_intervention / health_education / medication_care / diet_guidance / rehabilitation / discharge_prep / observation / other';
COMMENT ON COLUMN nursing_plan_item.source_type  IS 'assessment_rule / ai_suggested / nurse_manual';
COMMENT ON COLUMN nursing_plan_item.priority     IS 'low / normal / high / urgent';
COMMENT ON COLUMN nursing_plan_item.nurse_action IS 'accept / modify / reject';
CREATE INDEX ix_nursing_plan_item_plan ON nursing_plan_item (nursing_plan_id);

-- ----------------------------
-- 4. template_approval  模板审批记录
-- ----------------------------
CREATE TABLE template_approval (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type     VARCHAR(64)  NOT NULL,
    target_id       BIGINT       NOT NULL,
    approval_status VARCHAR(32)  NOT NULL DEFAULT 'pending',
    submitted_by    BIGINT       NOT NULL DEFAULT 0,
    submitted_at    TIMESTAMP(3),
    approved_by     BIGINT       NOT NULL DEFAULT 0,
    approved_at     TIMESTAMP(3),
    rejected_by     BIGINT       NOT NULL DEFAULT 0,
    rejected_at     TIMESTAMP(3),
    reject_reason   TEXT         NOT NULL DEFAULT '',
    review_note     TEXT         NOT NULL DEFAULT '',
    creator         VARCHAR(64)  NOT NULL DEFAULT '',
    updator         VARCHAR(64)  NOT NULL DEFAULT '',
    create_time     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  template_approval IS '量表/宣教方案/知情同意书模板发布前的人工审批流水';
COMMENT ON COLUMN template_approval.target_type     IS 'assessment_scale_version / education_program_version / consent_document_version / quality_review_template';
COMMENT ON COLUMN template_approval.approval_status IS 'pending / under_review / approved / rejected / revoked';
CREATE INDEX ix_template_approval_target ON template_approval (target_type, target_id);

-- ----------------------------
-- 5. operation_audit_log  操作审计日志
-- ----------------------------
CREATE TABLE operation_audit_log (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id       VARCHAR(128) NOT NULL DEFAULT '',
    operator_id    BIGINT       NOT NULL DEFAULT 0,
    operator_name  VARCHAR(128) NOT NULL DEFAULT '',
    operator_role  VARCHAR(64)  NOT NULL DEFAULT '',
    operation_type VARCHAR(64)  NOT NULL,
    target_type    VARCHAR(64)  NOT NULL DEFAULT '',
    target_id      BIGINT       NOT NULL DEFAULT 0,
    target_no      VARCHAR(64)  NOT NULL DEFAULT '',
    before_data    JSONB        NOT NULL DEFAULT '{}'::JSONB,
    after_data     JSONB        NOT NULL DEFAULT '{}'::JSONB,
    diff_summary   TEXT         NOT NULL DEFAULT '',
    result_status  VARCHAR(32)  NOT NULL DEFAULT 'success',
    error_message  TEXT         NOT NULL DEFAULT '',
    client_ip      VARCHAR(64)  NOT NULL DEFAULT '',
    user_agent     VARCHAR(500) NOT NULL DEFAULT '',
    occurred_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator        VARCHAR(64)  NOT NULL DEFAULT '',
    updator        VARCHAR(64)  NOT NULL DEFAULT '',
    create_time    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted        SMALLINT     NOT NULL DEFAULT 0
);
COMMENT ON TABLE  operation_audit_log IS '全域操作审计；高频写入表，建议按月分区或归档到时序存储';
COMMENT ON COLUMN operation_audit_log.operation_type IS 'create / update / delete / confirm / approve / reject / sign / revoke / export / login / logout';
COMMENT ON COLUMN operation_audit_log.result_status  IS 'success / failure / partial';
COMMENT ON COLUMN operation_audit_log.before_data    IS '变更前快照（仅变更字段）；创建类操作为空对象';
COMMENT ON COLUMN operation_audit_log.after_data     IS '变更后快照（仅变更字段）；删除类操作为空对象';
CREATE INDEX ix_audit_log_operator   ON operation_audit_log (operator_id, occurred_at DESC);
CREATE INDEX ix_audit_log_target     ON operation_audit_log (target_type, target_id);
CREATE INDEX ix_audit_log_trace      ON operation_audit_log (trace_id) WHERE trace_id <> '';
CREATE INDEX ix_audit_log_occurred   ON operation_audit_log (occurred_at DESC);


